rust-av/Av1an

main.py
=> Bruh 404 : add args parser

README.md, av1an.py
=> Use pathlib Paths + type annotations

README.md, av1an.py
* Resuming
* Checking encoded frame count
* Fixes and improvements
=> Encoding resume. Av1an 1.4

av1an.py
=> Restore terminal settings before exit

.codeclimate.yml, av1an.py
Refactoring functions to reduce cognitive complexity. ~This is still WIP so it is not ready, created PR so others can see progress/contribute.~ I am unable to completely reduce scene_detect to 5 or below so this is all set.
TODO:
=> Reduce Cognitive Complexity for code climate to increase maintainability

README.md
Preview:
https://github.com/nathanielcwm/Av1an/blob/patch-1/README.md
=> Clean up install instructions to make it easier to follow.

av1an.py
Still working on this so don't merge yet ;)
Changes so far:
- Reads total framecount from saved progress
- Resume now works even when only 1 chunk had been encoded
I'm gonna make it json also to avoid using `literal_eval` which is dirty and dangerous
=> [WIP] Resume improvements

utils/split.py
I missed an indent of 8 and there was an extra len call on a log message.
=> Fix indent and remove extra len

.github/workflows/tests.yml
This will add testing for x265 to the github actions
=> WIP: Add x265 testing

Av1an/chunk_queue.py, Av1an/compose.py
Implements the speed up from e3806cb4678853328d493e885f427ede1f968906 for the encoder pipes.
=> Add bufsize to encoder pipes

Av1an/split.py
Fix last frame getting added to split_locations in extra_split
=> Fix extra_splits: do not add last frame to split_locations

Av1an/aom_kf.py, Av1an/arg_parse.py, Av1an/bar.py, Av1an/chunk_queue.py, Av1an/concat.py, Av1an/config.py, Av1an/encode.py, Av1an/encoders/aom.py, Av1an/encoders/rav1e.py, Av1an/encoders/svtav1.py, Av1an/encoders/svtvp9.py, Av1an/encoders/vpx.py, Av1an/encoders/vvc.py, Av1an/encoders/x264.py, Av1an/encoders/x265.py, Av1an/ffmpeg.py, Av1an/fp_reuse.py, Av1an/logger.py, Av1an/pyscene.py, Av1an/setup.py, Av1an/split.py, Av1an/target_vmaf.py, Av1an/utils.py, Av1an/vmaf.py
This PR fixes 109 style and code warnings generated by PyCharm.
=> Fix style warnings

Av1an/encode.py, Av1an/encoders/aom.py, Av1an/encoders/encoder.py, Av1an/encoders/rav1e.py, Av1an/encoders/svtav1.py, Av1an/encoders/svtvp9.py, Av1an/encoders/vpx.py, Av1an/encoders/vvc.py, Av1an/encoders/x264.py, Av1an/encoders/x265.py, Av1an/setup.py
Moves default encoder options (default passes and default target vmaf range) into the encoder classes.
Also moves specific VVC behavior (yuv file creation and deletion) into more general before and after chunk encoding events.
=> Move default options and vvc yuv creation into encoder classes

Av1an/VMAF/target_vmaf.py, README.md
Needs ln from #143 and transform_vmaf from #146, so merge those first.
=> Provide guesswork math for 1-2 probe vmaf target

Av1an/bar.py, Encoders/svtav1.py
Uses SVT-AV1's new `--progress 2` mode to support updating the progress bar.
=> Add live updating progress bar for svt-av1

Av1an/arg_parse.py, Chunks/chunk_queue.py, Encoders/encoder.py, README.md, Scenedetection/pyscene.py, Startup/setup.py
now it can be the recommended method
=> Add vs_lsmash chunk method for mkv/mp4/m2ts 

Av1an/concat.py
I don't have access to Windows to test if I found all cases of missing `as_posix`, but this should fixe #187.
=> Add as_posix to ffmpeg concat command

av1an/fp_reuse.py
Fixes an issue with first pass reuse on 1 chunk.
=> Zero pad first pass file with 1 chunk

av1an/manager/Counter.py, av1an/manager/Manager.py, av1an/scenedetection/aom_kf.py, av1an/target_quality/target_quality.py
Also add parends around some if statements relating to tqdm to make them syntactically obvious and correct
=> Apply vmaf n_threads to probes as well to prevent cpu overallocation

docs/Encoders/aomenc.md
=> Updated aomenc.md again for even better documentation and recommendations

.github/workflows/tests.yml, Dockerfile, README.md
This will update the dockerfile to remove the need of sudo and add basic readme information on how to use the docker container   
Also fixes PR always failing due to docker action failing. Docker action will now only run on pushes to master
=> Docker readme and cleanup

Dockerfile, README.md
Update readme to fix word splitting on docker command
Format readme using remark
Use johnvansickles ffmpeg build, fixes issues with ffmpeg crashing causing all encodes to fail
=> Update readme, use johnvansickle ffmpeg build

av1an/manager/Queue.py
Signed-off-by: Luigi311 <luigi311.lg@gmail.com>
=> Fix error on 0 encoding chunks for resuming

Dockerfile
Signed-off-by: Luigi311 <luigi311.lg@gmail.com>
=> Docker: Add mkvmerge

av1an/project/Project.py
Tested locally, including blank Vapoursynth input and normal MKV input
file.
Fixes #222
=> Fix Vapoursynth input.

av1an/target_quality/target_quality.py
Based on discussion of #252 , Compute and set the VMAF threads based on OS CPUs to try and avoid over provisioning.
=> Determine VMAF threads value based on number of workers Closes #252

av1an/project/Project.py
Defaults to hybrid method in that case.
=> Fix None error when user has vpoursynth, but not ffms2 or lsmash

Dockerfile
Signed-off-by: Luigi311 <luigi311.lg@gmail.com>
=> Dockerfile: Add rust build

README.md
yes I know stereotypical "contribution"
=> spelling fix in the readme

Dockerfile
Fix docker build by using rust nightly
=> Use rust nightly

.github/workflows/tests.yml, Dockerfile
Adds docker build to all CI to test docker building
Adds pip install wheel to remove silent error with vapoursynth
=> Docker improvements

av1an-core/src/progress_bar.rs
Remove mutex and fix subtle flashing at the beginning.
=> Tweak progress bar

.github/workflows/tests.yml, .gitignore, Dockerfile
- Fix workflow to run with all rust build
- Fix dockerfile with all rust build
=> Fix workflow, Fix Dockerfile

av1an-cli/src/lib.rs, av1an-cli/src/main.rs, av1an-core/Cargo.toml, av1an-core/src/progress_bar.rs, av1an-pyo3/src/lib.rs
For stats nerds like myself. Example screenshot:
=> Add --verbose flag to show worker progress bars

av1an-core/src/vmaf.rs
Avoid to have adding a trailing comma to --vmaf-filter option.
Fixes #326
=> Fix --vmaf-filter handling in run_vmaf_on_chunk()

av1an-core/src/ffmpeg.rs, av1an-core/src/split.rs
I made some minor improvements to `ffmpeg.rs`. Commits should be self explanatory.
=> Small improvements to ffmpeg.rs

av1an-cli/src/main.rs
This is something the Python implementation did but removed and never added back until now.
=> Add output file confirmation prompt, improve error handling slightly

Cargo.lock, av1an-cli/src/lib.rs, av1an-core/Cargo.toml, av1an-core/src/broker.rs
Disabled setting thread affinity on platforms other than linux and windows. This should fix compilation on macos.
=> Fix compilation on macos

Cargo.lock, av1an-cli/src/lib.rs, av1an-core/Cargo.toml, av1an-core/src/progress_bar.rs, av1an-core/src/scene_detect.rs, av1an-core/src/settings.rs, av1an-core/src/util.rs, av1an-core/src/vmaf.rs
New CLI look:
Other changes:
- Now if the total fps is less than 1, we display seconds per frame instead of frames per second.
- Add `-y` flag to overwrite output file without confirmation
=> Better CLI interface

av1an-core/src/settings.rs, av1an-core/src/split.rs
In some rare cases scenes.json may be corrupted, which can happen if there is a power outage or other system failure at the exact moment that scenes.json is being written, causing scenes.json to be incomplete and thus fail to parse.
Old behavior:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)', av1an-core/src/settings.rs:552:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
New behavior:
```
Error: Failed to parse scenes file ".e86cc76/scenes.json", this likely means that the scenes file is corrupted
Caused by:
EOF while parsing a value at line 1 column 0
```
=> Better error handling if parsing scenes.json failed

av1an-core/src/broker.rs, av1an-core/src/encoder.rs, av1an-core/src/lib.rs, av1an-core/src/progress_bar.rs, av1an-core/src/scene_detect.rs, av1an-core/src/settings.rs, av1an-core/src/simd.rs
Also fix some clippy warnings.
=> Set `Stdio::null()` for ffmpeg/vspipe during scene detection

av1an-core/src/settings.rs
We should ideally still display both the stderr of the source pipe and
the ffmpeg filter pipe, but this should be good enough for the vast
majority of cases as displaying the stderr of both pipes requires a
slightly larger change which we can do in a later PR.
=> Display the stderr of the ffmpeg pipe when available

.mergify.yml
- Remove usage of deprecated "strict" param by using queues
- Add auto merge for stable backports
- Fix assignees for stable patches
=> Additional changes for mergify

av1an-core/src/ffmpeg.rs
=> Escape commas in escape_path_in_filter

av1an-core/src/encoder.rs
Correctly using log2. convertion to u32 should floor.
Less total lines
=> Correct and simplify tiles calculation

av1an-core/src/settings.rs
=> Warn about slowness when using "select" chunk method

Cargo.lock, Cargo.toml, av1an-core/Cargo.toml
Notably:
- parking_lot
- sysinfo
and many patch version bumps
=> Update several dependencies

av1an-core/Cargo.toml
=> fix indicatif

av1an-core/src/settings.rs
=> Fix extra splits and zones handling with split method none

README.md
=> Add compilation instructions for Windows

docs/Encoders/svt-av1.md
Adding some essential SVT-AV1 documentation. Requesting feedback before merge.
closes #592
=> docs: First pass for SVT-AV1 documentation

Cargo.lock, Cargo.toml, av1an-cli/src/lib.rs, av1an-core/src/scene_detect.rs
- Fix scenechange progress bar when zones active
- Fix issue where wrong number of frames are read in scenechange with zones active
- Fix formatting of zones help text
=> Zones fixes

Dockerfile
- Reenabled cargo-chef because the [issue](https://github.com/master-of-zen/Av1an/issues/642) has been [fixed](https://github.com/LukeMathWalker/cargo-chef/pull/129#issuecomment-1172378703).
- Removed `cacher` stage (not necessary, seems to be there from some older version of the Dockerfile)
- Changed `pacman -Syyu` to `pacman -Syu` and add `-needed` (in case packages will be added to the base docker image)
=> Reenable cargo chef

av1an-core/src/encoder.rs
=> Fix usage of --quiet flag

av1an-core/src/parse.rs
=> Fix x26* progress bar

Cargo.lock, Cargo.toml, av1an-core/Cargo.toml
Just before trying to bump everything to 0.4
=> Remove patches and bump av-scenechange

av1an-core/src/parse.rs
=> Fix x26* progress parsing for real

docs/TargetQuality.md
=> Add some target quality docs

.github/workflows/tests.yml
Updates actions to the latest version
=> Tests: update actions

av1an-core/src/broker.rs, av1an-core/src/settings.rs
Removes tpl work around and use chunk_queue size for total chunks
=> Remove tpl

av1an-core/src/progress_bar.rs, av1an-core/src/scene_detect.rs, av1an-core/src/settings.rs
=> Fix estimated fps when using --resume flag

av1an-core/src/context.rs
This may mitigate #773, further testing is required to verify. Overall it should slightly improve performance as well.
=> Only get frame rate from Vapoursynth once while creating queue

README.md, av1an-core/src/context.rs, av1an-core/src/lib.rs, av1an-core/src/settings.rs, av1an-core/src/vapoursynth.rs, av1an/src/main.rs, docs/CLI.md
Reverts master-of-zen/Av1an#796
Closes #797
=> Revert "Remove support for DgDecNv"

av1an-core/src/settings.rs
Now that https://gitlab.com/AOMediaCodec/SVT-AV1/-/merge_requests/2165 is merged, av1an can support this as well.
=> Support grain tables for SVT-AV1

Cargo.lock, av1an-core/Cargo.toml, av1an-core/src/ffmpeg.rs, av1an/Cargo.toml
=> Support ffmpeg 7.0

Cargo.lock, av1an-core/Cargo.toml
=> Use updated av-scenechange with threaded ffmpeg decoder

.github/workflows/windows-build.yml
So that the date and the associated commit is updated in the github release
=> Delete tag before making a release

av1an-core/src/encoder.rs
=> Fix x265 target quality

av1an-core/src/encoder.rs, av1an/src/main.rs
=> Print available encoder versions in `--version`

.github/workflows/tests.yml
This should help improve organization and visibility of where failures are occurring.
=> Split CI into separate jobs

av1an-core/src/broker.rs, av1an-core/src/context.rs, av1an-core/src/logging.rs, av1an-core/src/target_quality.rs
This PR depends on PR #969 and also fixes the stray commented out code line. It also addresses Issue #934 by providing feedback on Target Quality processing for each chunk. See below:
[demo.webm](https://github.com/user-attachments/assets/26881534-5ecd-4f2d-b61d-2e0e8497c08f)
Thanks,
\- Boats M.
=> Add Target Quality feedback to mini progress bar per chunk

.github/workflows/tests.yml, av1an-core/src/broker.rs, av1an-core/src/chunk.rs, av1an-core/src/chunk/tests.rs, av1an-core/src/concat.rs, av1an-core/src/concat/tests.rs, av1an-core/src/context.rs, av1an-core/src/encoder.rs, av1an-core/src/encoder/tests.rs, av1an-core/src/ffmpeg.rs, av1an-core/src/lib.rs, av1an-core/src/logging.rs, av1an-core/src/parse.rs, av1an-core/src/parse/tests.rs, av1an-core/src/progress_bar.rs, av1an-core/src/scene_detect.rs, av1an-core/src/scenes.rs, av1an-core/src/scenes/tests.rs, av1an-core/src/settings.rs, av1an-core/src/split.rs, av1an-core/src/split/tests.rs, av1an-core/src/target_quality.rs, av1an-core/src/target_quality/tests.rs, av1an-core/src/util.rs, av1an-core/src/util/tests.rs, av1an-core/src/vapoursynth.rs, av1an-core/src/vmaf.rs, av1an/build.rs, av1an/src/main.rs, rustfmt.toml
Quite substantial quality improvement to the formatting of the project
=> Improvement on rustfmt.

av1an-core/src/loadscript.vpy
=> feat: Set Number of Threads for VScore to 1 When No VPY File Is Specified

Cargo.lock, av1an-core/Cargo.toml, av1an-core/src/target_quality.rs
With this change, the `spline` crate is also removed. Some simple functions are added for linear, natural cubic and PCHIP interpolations.
Subject to be improved further in the future (if we come up with even better methods). The current method will be:
- Start with binary search (we do it already): First Round (with 0 known data point)
- Binary again for the second round (we do it already): Second round (with 1 known data points)
- Linear interpolation (we do it already): Third round (with 2 known data points)
- Natural Cubic Spline: Fourth round (with 3 known data points)
- For the 5th probe, use PCHIP Interpolation (with 4 known data points)
- At this point (6 and rest rounds) only do binary search until the exit condition (because generally this point indicates a problem and it should …
=> Further improvements for CRF search

av1an-core/src/context.rs, av1an-core/src/scenes.rs
=> Export Scenes as Pretty Json

av1an/src/main.rs, site/src/Cli/encoding.md, site/src/Features/TargetQuality.md, site/src/av1an.md
=> Change default encoder from aomenc to svt-av1
