- av1an.py
The command `/usr/bin/env python` uses the Python 2 interpreter (at least on my machine).
By changing the shebang to explicitly use the Python3 interpreter, the problem should not happen anymore.
> Change shebang to use python3

- av1an.py
The python docs recommends the use of the `subprocess` module over the `os.system` function.
It also makes logging easier and cross-platform compared to the existing solution (and also solves a problem I had where ffmpeg didn't create the segment files)
> Replace os.system with subprocess.call and use it for logging

- av1an.py
The threshold being passed to scenedetect needs be a float, but is set as a string in the option parser. This leads the scene detection failing with `Error in PySceneDetect` when setting `-tr 40`. This PR sets the type of the threshold option to be a float.
> Fix manually specifying scenedetect threshold

- av1an.py
Av1an work on video with non-exact framerates which is basically all videos.
> Closes #41 by using frame numbers instead of timecodes, which makes

- av1an.py
Due to the not it looks like the vmaf_path path was never actually being used correctly. If it was not provided it would set the path for the model to None but if it was provided the model was never being populated.
- Original
- ```bash av1an.py -i short.mkv --vmaf --vmaf_path /usr/local/share/model/vmaf_v0.6.1.pkl ```
- ```bash ffmpeg -y -hide_banner -loglevel error -i .temp/split/0021.mkv -i .temp/encode/0021.ivf  -filter_complex "[0:v][1:v]libvmaf" -max_muxing_queue_size 1024 -f null - ```
- ```bash av1an.py -i short.mkv --vmaf ```
- ```bash ffmpeg -y -hide_banner -loglevel error -i .temp/split/0021.mkv -i .temp/encode/0021.ivf  -filter_complex "[0:v][1:v]libvmaf=model_path=None" -max_muxing_queue_size 1024 -f null - ```
- New
- ```bash av1an.py -i short.mkv --vmaf --vmaf_path …
```
> Fix get_vmaf ffmpeg model not being used

- av1an.py
This will allow the user to define how many probes to set and what the min and max range should be. It will auto space with whole numbers only and if provided more steps than the range allows it will not do duplicate runs. Also switched the tg_vmaf parameter to be -- since its not really a short command so it should match up with the other long commands.  
New Arguments:
- --vmaf_steps # 
- number of steps to probe between min and max.
- --min_cq # 
- setting the min cq to probe. Defaults to 20.
- --max_cq # 
- setting the max cq to probe (inclusive). Defaults to 63.
> Allow dynamic setting of target vmaf probes

- av1an.py
The goal of config files should be to allow users to create/edit them manually to avoid command-line clutter, so this will make this possible.
> Config file saved in JSON rather than pickle format for easy editing

- av1an.py
Sometimes the container has the frame count and it's faster to just use that rather than count frames with `ffmpeg`. Requires `ffprobe` to be available, I'm not sure how common this is amongst `ffmpeg` installs.
See: https://stackoverflow.com/questions/2017843/fetch-frame-count-with-ffmpeg
Imports `subprocess.PIPE` and `subprocess.STDOUT` for cleaner code.
> Minor fixes

- av1an.py
Smooths the time remaining and fps calculation in the progress bar. Fixes #68.
Since the average is smoothed so much, we need to reset the progress bar on the first update, otherwise it takes about 1000 frames for the fps to reach its correct value after no updates during the first pass.
> Smooth ETA and FPS calculation

- appveyor.yml
This PR modifies the AppVeyor configuration to attach the `av1an.exe` binary to the GitHub release page on a tag or release. You can see [this test release](https://github.com/EwoutH/Av1an/releases/tag/1.11-test0) as an example.
To enable uploading to GitHub Releases, you need update this patch with your personal authentication token. You can generate one on https://github.com/settings/tokens/new (select `public_repo` as scope), and then encrypt it with https://ci.appveyor.com/tools/encrypt. Replace the current token on line 21 (after `secure:`) in the `appveyor.yml` file.
> AppVeyor: Deploy on tag/release

- av1an.py
```
Traceback (most recent call last):
File "av1an.py", line 1151, in <module>
main()
File "av1an.py", line 1144, in main
Av1an().main_thread()
File "av1an.py", line 1138, in main_thread
self.main_queue()
File "av1an.py", line 1124, in main_queue
self.video_encoding()
File "av1an.py", line 1106, in video_encoding
self.encoding_loop(commands)
File "av1an.py", line 1018, in encoding_loop
with concurrent.futures.ThreadPoolExecutor(max_workers=self.d.get('workers')) as executor:
AttributeError: module 'concurrent' has no attribute 'futures'
```
> Fix module 'concurrent' has no attribute 'futures'

- utils/aom_keyframes.py
Added -w and -h params to the command used to call the aomenc encoder when using aom_keyframes as splitting method. Not using those params cause an error in aomenc with some files.
> FIx for video split using aom_keyframes

- utils/ffmpeg.py
In the concat file, the files were listed as 
> file 'path'
so if in the path there was a ' the result were 
> file 'path1'path2'
and ffmpge would read only path1 and throw an error because it didn't find the file.
With this commits now all the ' in the path are replaced with '/'' so ffmpeg can read the path correctly.
> Added support for ' in the input's filename

- av1an.py
- utils/aom_keyframes.py
- utils/arg_parse.py
- utils/pyscenedetect.py
This PR works towards making splits less frequent than the encoder's key frame placement.
This PR adds the option `--min_scene_len` to specify the minimum number of frames in a chunk. This applies to scenedetect and aom_keyframe split methods. When this option is not set, the split behavior is unchanged.
Libaom's key frame placement was recently changed to include a lower bound on the distance between key frames (used by specifying`--kf-min-dist`) ([libaom commit](https://aomedia.googlesource.com/aom/+/ce97de2724d7ffdfdbe986a14d49366936187298)). This changes the way aom decides key frame placements. This PR updates the aom key frame split method to match the new aom code that accounts for this minimum distance.
> Add option for minimum number of frames in a chunk

- av1an.py
- utils/arg_parse.py
This PR uses the choices option in argparse for validating if the split method is correct. This allows for argparse to print an error so 3 lines in av1an.py checking for an invalid choice can be removed.
The new error message.
```
av1an.py: error: argument --split_method: invalid choice: '1324' (choose from 'pyscene', 'aom_keyframes')
```
It also prints out the choices in `--help`.
```
--split_method {pyscene,aom_keyframes}
Specify splitting method
```
> Use argparse for split method choice validation

- utils/dynamic_progress_bar.py
This PR prints out encoder errors if the encoder crashes. This helps troubleshoot invalid encoder options.
Consider this invalid command
```
python ./av1an.py -i source.mkv -enc aom -v ' --invalid option '
```
Before, the error message is unhelpful
```
Queue: 2 Workers: 2 Passes: 2
Params: --invalid option
0%|                                                                                                                               | 0/5111 [00:00<?, ?fr/s]
Encoding failed, check validity of your encoding settings/commands and start again
fish: “python ./av1an.py -i source.mkv…” terminated by signal SIGKILL (Forced quit)
```
Now it detects the encoder error and prints out the encoder's error message
```
Queue: 2 Workers: 2 Passes: 2 …
```
> Report encoder errors

- av1an.py
- utils/aom_keyframes.py
- utils/arg_parse.py
- utils/compose.py
- utils/split.py
This PR makes the aom keyframe split method use similar params to the first pass run on chunks. This will allow for reusing the first pass stat file on the chunks in a later PR.
> Make aom keyframe split 1st pass match chunk 1st pass

- av1an.py
- utils/utils.py
A user on the discord reported a bug on Windows. There were some cases where Paths weren't converted to strings. It works fine on linux but causes problems on Windows. This also fixes passing the built in `input` function instead of the input path to a couple functions.
> Fix using input instead of self.input and add as_posix on Paths

- utils/utils.py
I added a lock for when a encoding process need to read/write the done.json file. Without it, it may happen that two process read the file before writing the result, and then the second one to write the result would overwrite the result of the first.
> Added lock to I/O operations on done.json

- av1an.py
- utils/__init__.py
- utils/arg_parse.py
- utils/boost.py
- utils/compose.py
- utils/firstpassreuse.py
This PR allows for the reuse of the first pass stats file generated in the aom_keyframes split method to be used on the chunks. This will save time from not redoing the first pass on each chunk and may allow for chunked VBR encoding.
> Reuse first pass from AOM keyframe split on the chunks

- av1an.py
- utils/boost.py
- utils/compose.py
- utils/firstpassreuse.py
This simplifies the logic so that first pass reuse modifies the commands directly instead of relying on aom composing function, boost, and target vmaf.
> Simplify first pass reuse command generation

- utils/aom_kf.py
This prevents a `FileNotFoundError` stack trace being printed out if the first pass for aom_keyframes crashes.
Old error message:
```
Aom first pass encountered an error: 1                                                                                                                                                                                 
Error: Unrecognized option --invalid                                                                                                                                                                                   
Usage: aomenc <options> -o dst_filename src_filename                                                                                                                                                                   
Use --help to see …
```
> Explicitly terminate on aom keyframe split failure

- Av1an/vmaf.py
This fixes [plonk420's issue](https://discord.com/channels/587033243702788123/686197633181810720/733181191770996756) reported on discord. 
`call_vmaf` puts the vmaf log file in the same directory as the source video. This works well for target vmaf, but it doesn't make sense for the final vmaf plot. It also causes problems if the user doesn't have write permissions to the directory the source video is in. This PR puts the log in the output directory as well as as small refactors to `call_vmaf` and `plot_vmaf`.
> Put vmaf log in destination folder & use Path instead of string

- Av1an/arg_parse.py
This PR takes advantage of argument groups in argparse.
Help message before:
```
optional arguments:
-h, --help            show this help message and exit
--input INPUT [INPUT ...], -i INPUT [INPUT ...]
Input File
--temp TEMP           Set temp folder path
--output_file OUTPUT_FILE, -o OUTPUT_FILE
Specify output file
--scenes SCENES, -s SCENES
File location for scenes
--split_method {pyscene,aom_keyframes}
Specify splitting method
--extra_split EXTRA_SPLIT, -xs EXTRA_SPLIT
Number of frames after which make split
--min_scene_len MIN_SCENE_LEN
Minimum number of frames in a split
--threshold THRESHOLD, -tr THRESHOLD
PySceneDetect Threshold
--reuse_first_pass    Reuse the first pass from aom_keyframes split on the chunks
--passes {1,2}, -p {1,2}
Specify encoding passes
--video_params …
```
> Use argparse groups for better help message

- Av1an/arg_parse.py
- Av1an/chunk_queue.py
This PR introduces the option of using [ffmpeg's select filter](https://ffmpeg.org/ffmpeg-filters.html#select_002c-aselect) to create the chunks. This is enabled with `--chunk_method select`. This has the advantage of not requiring intermediate chunk files written to disk and being able to split on non-keyframes. The downside to this is increased time as ffmpeg needs to seek to the frames.
Performance on 53000 frame 1080p encode with libaom cpu-used 6:
segment: 4813.7s
select: 6853.3s
An extra 34 minutes, but this depends on the number of frames and becomes less important on lower cpu-used values. In addition, the select encode had an extra chunk because it was able to split on non-keyframes.
> Add the option for chunks to use the select filter instead of segmenting to disk

- Av1an/arg_parse.py
- Av1an/chunk_queue.py
- Av1an/setup.py
This PR introduces the option of using vapoursynth and ffms2 to create the chunks. This is enabled with `--chunk_method vs_ffms2`. This has the advantage of being quick, not requiring intermediate chunk files written to disk, and being able to split on non-keyframes. The only downside is the requirement of having vapoursynth and ffms2 installed.
Performance on 53000 frame 1080p encode with libaom cpu-used 6:
segment: 4813.7s
vs_ffms2: 4796.0s
> Add the option for chunks to use vapoursynth + ffms2

- Av1an/setup.py
This fixes a bug where if you wanted to set only the min q or only the max q, it would override your option with the default.
> Fix target vmaf min/max q default setting

- Av1an/aom_kf.py
- Av1an/bar.py
- Av1an/chunk.py
- Av1an/chunk_queue.py
- Av1an/compose.py
- Av1an/concat.py
- Av1an/encode.py
- Av1an/ffmpeg.py
- Av1an/setup.py
- Av1an/target_vmaf.py
- Av1an/utils.py
- Av1an/vmaf.py
- Av1an/vvc.py
This fixes handling path with spaces in them.
av1an stores commands in strings, which are split before passing them to the subproces module. This causes any path with spaces in it to be split in multiple parts.
This patch changes all commands (i hope i found all) to be stored in tupel, which can be directly passed to the subprocess module, eliminating the need for splitting them.
For concat i have used shlex to quote paths, which can quote/escape most (if not all) unicode charactes correctly so that ffmpeg sees the correct path.
> Fix handling path with spaces

- Av1an/chunk_queue.py
This line got lost in in 3d41cafe625c5589460e8711892bbd212b4255c1 when reverting  69a73343b8e9e0dd9f975f28ced9acdb161829ff
> Fix missing line in split_locations

- Av1an/arg_parse.py
- Av1an/bar.py
- Av1an/encoders/__init__.py
- Av1an/encoders/svtvp9.py
- Av1an/setup.py
- Av1an/target_vmaf.py
Adds initial support for SVT-VP9 (#124). Target VMAF is not yet working.
> Add initial svt-vp9 support

- .github/workflows/tests.yml
Recently, Bitbucket stopped supporting Mercurial repositories. x265 didn't migrate in time, so their repository can no longer be accessed until they migrate to git. This PR switches from mercurial on bitbucket to git on github for installing x265.
> Fix failing x265 test

- Av1an/ffmpeg.py
Map all audio and subtitle tracks for the audio file instead of just the first (ffmpeg default).
> Map all audio tracks in extract_audio()

- Av1an/encoders/svtav1.py
SVT-AV1 allows for setting the q value with `--qp` or `-q`, but target vmaf was only looking for `--qp`.
> Support SVT-AV1 -q for target vmaf

- Av1an/bar.py
- Av1an/encode.py
`tqdm` bar has an `__exit__` method run when the bar is destroyed on program exit. This causes the bar to be printed out after the finished message. Calling `tqdm.close()` explicitly before printing the finish method fixes this problem.
Before:
```
Queue: 2 Workers: 16 Passes: 2
Params: --cpu-used=6 --end-usage=q --cq-level=40
99%|████████████████████████████████████████▋| 280/282 [00:54<00:00,  4.86fr/s]Finished: 92.2s
100%|█████████████████████████████████████████| 282/282 [00:54<00:00,  5.15fr/s]
```
After:
```
Queue: 2 Workers: 16 Passes: 2
Params: --cpu-used=6 --end-usage=q --cq-level=40
100%|█████████████████████████████████████████| 282/282 [00:55<00:00,  5.12fr/s]
Finished: 92.4s
```
> Fix extra tqdm print

- Av1an/VMAF/target_vmaf.py
This transformation of vmaf values maps more linearly to cq values, which should improve the search accuracy.
vmaf vs cq:
transformed vmaf vs cq:
> Vmaf transform

- Av1an/VMAF/target_vmaf.py
Redesigned the search to use upper and lower bounds variables.  Bad case happens for example when the target vmaf is between vmaf_cq[-3] and vmaf_cq[-1] but it's searching between vmaf_cq[-2] and vmaf_cq[-1].  Also cleaned the next_q dead code in the main loop.  I've never used python so I don't know how to test this code
> Fix search algorithm

- Startup/setup.py
- Startup/validate_commands.py
Clears up the wording of the parameter validation warning and fixes the SVT-VP9 error when no video params are specified due to `validate_input` being run before `SvtVp9.is_valid`.
Fixes #158
> Fix English & run validate params after encoder is set up

- Startup/setup.py
Fix double suffix issue and if no output is provided it will now use _{encoder} instead of always appending _av1 even when not encoding in av1.
Signed-off-by: Luis Garcia <luigi311.lg@gmail.com>
> Fix output double suffix, default will append _{encoder} instead of _av1

- Startup/validate_commands.py
x265 was failing because the video parameter list was only discarding digits but not string arguments. So it was doing a check on ["-p","slow","--crf"] so when it got to slow and checked if it was a validate argument for x265 it was failing. This now changes it to generate the list with everything that starts with - which should be all the flags and leave out any strings or numbers. 
Changes the exit code to 1 if not using --force to report that there was an error.
Signed-off-by: Luis Garcia <luigi311.lg@gmail.com>
> Fix x265 commands

- Startup/setup.py
`args.output_file.stem` incorrectly removed any paths before the file name (`folder/file` would become just `file`).
> Support output files in different folders

- .github/workflows/tests.yml
Added a python requirement to the actions to prevent a warning message.
Moved the matrix flag to the end so things like the baseline wont randomly add spaces in between flags and you also know exactly where to look for the flags its testing
Added du on the output of av1an to validate that the encode did happen which will catch issues like x265 encoding failing but not reporting an error on the CI because the exit code didnt change from 0
Replace the deprecated set-env function with the new github env
x265 is now built into the base image so we don't need to build it here anymore
Signed-off-by: Luis Garcia <luigi311.lg@gmail.com>
> Actions: Check if encoded file exists + misc

- Av1an/ffmpeg.py
Since we only have one input file, the '-map 0' was unnecessary,
and using '-vn' is a more reliable method for disabling video.
Added '-sn' and '-dn' for good measure, which disables subtitles and
data streams, respectively.
Fixes #151
> Improve extract_audio ffmpeg command.

- Av1an/arg_parse.py
- Av1an/encode.py
- Av1an/ffmpeg.py
- Av1an/split.py
- Av1an/utils.py
- Av1an/vapoursynth.py
- Chunks/chunk_queue.py
- Scenedetection/aom_kf.py
- Scenedetection/pyscene.py
Supports:
* Pyscenedetect chunking
* aom_keyframes chunking
* Automatic detection of input as Vapoursynth script.
* Cleaned up fast frame counting into unified method "frame_probe_fast"
Areas for improvement:
* Windows support
* vspipe arg passing
* Update README with details on Vapoursynth integration
* Cleanup piping command generation that's sprinkled throughout the project, including moving ffmpeg pipe generation into the `ffmpeg.py` file.
* Clean up names that include "ffmpeg" in a few places, when they aren't actually guarranteed to be ffmpeg any more (and may be vspipe instead). 
Fixes #173
> Vapoursynth Support - Part 1

- Encoders/x265.py
Per the x265 documentation, if `--frames` is specified, the rate control
can use the information for better encoding decisions.
In addition, we should be encoding an exact number of frames anyways.
This might benefit x264 as well, but I'm not sure if that's guarranteed.
It's trivial to add, so it may be worth adding anyways.
See docs around `--frames` option: https://x265.readthedocs.io/en/master/cli.html#input-output-file-options
Testing note: I tested what happens with something like vspipe returns
less than the specified number of frames and things work "just fine" -
the encoder exits with no error message and the stream isn't corrupted.
> Pass frames to x265 for a given chunk.

- Encoders/svtav1.py
This should fix a command syntax error I encountered when encoding two-pass with SVT-AV1.
> Fix SVT-AV1 two-pass command syntax

- .github/workflows/tests.yml
- Startup/validate_commands.py
- requirements.txt
- setup.py
I also found it to be more accurate for this use case
levenshtein:
'--kxf-max-dusst' isn't a valid param for aom. Did you mean '--qm-max'?
sequencematcher:
'--kxf-max-dusst' isn't a valid param for aom. Did you mean '--kf-max-dist'?
> remove fuzzywuzzy/levenshtein and use difflib sequencematcher

- .github/workflows/tests.yml
- TargetQuality/per_shot.py
- TargetQuality/target_quality.py
- VMAF/vmaf.py
This will add testing for the vmaf and vmaf_plots arguments since they are currently broken and gets changed every so often.
I also moved generic vmaf functions out of the tartget_quality file since they do not belong there.
Action will also use tree -a instead of ls -a so a more complete output is shown
vmaf and vmaf_plots are currently broken due to the get_percentile function not working
> Add testing for vmaf and vmaf_plots, move non target_quality specific functions to vmaf.py

- Startup/file_validation.py
Currently in the inputs list if a directory is in first position the following inputs are ignored. The PR allows to have several directories or files in input, in any order. All input files and files in directories will be taken into account.
For example if we have : -i dir1 file1 dir2 file2
the files taken into account will be file1, file2 and all relevant files from dir1 and dir2
> input: to be able to have several directories and files

- Managers/Manager.py
The call to proj.outputs_filenames() is useless since it is already before called in create_project_list()
> remove unnecessary proj.outputs_filenames()

- Av1an/split.py
Those write_scenes_to_file are never called since the case with project.scenes is handled in the previous if in split_routine
> remove unnecessary write_scenes_to_file

- .github/workflows/tests.yml
Update the matrix to test baseline and target_quality on all encoders but svt-vp9 and vvc. To add more flags that needs to be tested on all encoders you need to add it name:[] and then create an include for it with just the same name and the flag for it.
> Actions: Test baseline and target_quality for all encoders

- README.md
- av1an/arg_parse.py
- av1an/manager/Counter.py
- av1an/project/Project.py
- av1an/scenedetection/__init__.py
- av1an/scenedetection/aom_kf.py
- av1an/scenedetection/ffmpeg.py
- av1an/scenedetection/pyscene.py
- av1an/split.py
- av1an/target_quality/target_quality.py
- av1an/vmaf/vmaf.py
- setup-minimal.py
Add ffmpeg splitting, add --quiet to stop tqdm from loading, make scenedetect and tqdm not strictly required, add setup-minimal for av1an-minimal, a version with much fewer deps, when using --quiet av1an exposes the number of frames that have been encoded
> Qencoder compatibility patch

- av1an/encoder/svtav1.py
SVT-AV1's Docu only specifies using -q instead of --qp. This change was introduced with the introduction of crf based encoding instead of fixed qp.
Changed the value in the default args to match that.
> Changed default args on SVTAV1

- .github/workflows/tests.yml
- Dockerfile
- README.md
Docker:
- The docker image will now be based on luigi311/encoders-docker where all the encoders and other tools are built so the docker build github action doesnt take forever.
README:
- Updated docker readme information to include :latest tag and --rm to prevent stale images
- Added descriptions for all the available tags 
Actions:
- Cleanup dependencies since the base image contains almost everything
- Add vs chunking test
- Use python setup.py install as pip install -r requirements was broken
- Cat av1an log for success and failures
- Will now tag with latest, master, #.## and sha-###### to allow users to backtrack to a previous version if necessary
> Docker: Use luigi311/encoders-docker, Update readme, update actions

- README.md
- av1an/arg_parse.py
This adds documentation in both the README and commandline arguments.
Hopefully this will prevent confusion like in #222.
> Make Vapoursynth support more apparent.

- av1an/vmaf/vmaf.py
Mitigates the uncommon 100VMAF issue in continuous motion scenes.
https://slow.pics/c/lUAHEERa
1st pic is what happens normally:
```
01:06:54 AM Chunk: 00000, Rate: 4, Fr: 127
Q: [32, 55], Early Skip High CQ
Vmaf: [100.0, 100.0]
Target Q: 55 VMAF: 100.0
01:06:56 AM Chunk: 00001, Rate: 4, Fr: 127
Q: [32, 55], Early Skip High CQ
Vmaf: [100.0, 98.65]
Target Q: 55 VMAF: 98.65
```
2nd pic is what happens with the patched build:
```
06:45:49 PM Chunk: 00000, Rate: 4, Fr: 127
Q: [32, 50, 52, 55]
Vmaf: [100.0, 94.36, 92.91, 90.82]
Target Q: 47 VMAF: 95.86
06:45:51 PM Chunk: 00001, Rate: 4, Fr: 127
Q: [32, 50, 52, 55]
Vmaf: [100.0, 92.23, 91.15, 88.29]
Target Q: 41 VMAF: 96.2
```
with this sample: https://drive.google.com/file/d/1YBY7sbO2-3SvNajIAOFtvzWKRFX5cGW-/view?usp=sharing
This basically …
> Fixes VMAF calculation using the native VMAF n_subsample

- av1an/target_quality/target_quality.py
Hi, 
just some minor changes that happened when I tried to fully understand your probe logging code.
P.S.: I think the log is not ideal for the fast_search results. It will print the targeted VMAF as the desired VMAF should be met by encoding with the calculated q.
> Annotate methods for probe logging and simplified case distinction

- av1an/encoder/encoder.py
- av1an/encoder/vvc.py
- av1an/manager/Pipes.py
- av1an/target_quality/target_quality.py
- av1an/vmaf/vmaf.py
Pass references to created pipes to the process_pipe functions, such that any remaining pipes can get killed. Prevents stray applications taking up RAM.
For the future, this might also make it easier to log error output from these pipes when an encoder error occurs due to issues with the piping or input files. 
Tested on Windows 10, with vspipe (lsmash I believe).
> Kill auxiliary pipes when main encode/process is finished

- av1an/arg_parse.py
- av1an/project/Project.py
By ending the output filename with `\` or `/`, it will be interpreted as a folder. Users will therefore be able to output encoded files to that folder. Encoded files take the standard name as if no output name were specified. The same applies to temp paths.  
Note that the temp folder will be created if it does not exist, but it will not be deleted. Each project/encode temp folder will respect the setting, but the temp folder that is specified by the user will not be deleted, in case that folder is used for other purposes, or in the event that user specifies both temp and output as the same folder. (Which is fully supported in with this pull request!)
This change forced me to change the default arg  type from Path to str, since it seems like Path objects remove the slashes at the ends of …
> Allow folder as output for Av1an

- av1an/vapoursynth.py
Reported on discord, when using vapoursynth, files with uncommon characters such as ä, ö or ü.
Issue was reproduced and then fixed for me (on Windows 10, vapoursynth with lsmash) by changing loadscript.vpy encoding to utf-8. I believe python defaults to different encodings per system, and uses a different default codec causing this issue on Windows, and potentially on other OSes as well.
> Use utf-8 encoding for loadscript.vpy, handles nonstandard characters.

- av1an/scenedetection/aom_kf.py
Added support for recent aomenc versions, which have added fields in first pass. 
Added a try/except that first tries this new mode, then defaults to old parsing, to ensure backward compatibility. 
Should fix the failing test.
> Aom firstpass fix

- av1an/encoder/svtav1.py
- av1an/target_quality/target_quality.py
So, these are the small changes I've been working on. 
aomenc: Removing ` "--enable-rect-tx=0"` fixes some crashes, and adding some new options speeds up the quality analysis in target_quality mode without impacting VMAF analysis scores in both live-action and animation.
SVT-AV1: Fixing the command parsing for CRF in target_quality mode, as well as adding `--keyint 240` for better efficiency and speed over the default 33 frame keyframe limit, both in normal default encoding mode and target_quality. Also, reenabling HME since it actually speeds up the encoder a bit. Since CRF is now used, tpl-la has to be kept enabled as well :smile: 
Other: probing_rate fix by making sure that all probing_rates below 4 are active. Before, 3 would go up to 4. Now, it just works.
> Making aom+SVT-AV1 target_quality faster and SVT-AV1 fixes

- av1an-core/src/target_quality.rs
x265 frame-thread has a max value of 16 https://x265.readthedocs.io/en/3.1/cli.html#cmdoption-frame-threads setting it to any higher will cause it to fail with a error stating that frame-threads is not set or just freeze causing issues with av1an. This only manifests on machines with lots of cores and with videos that are a big enough length that x265 is able to try to use 16+ frame threads.
Signed-off-by: Luigi311 <luigi311.lg@gmail.com>
> TargetQuality: x265 frame-thread max 16

- .github/workflows/tests.yml
- av1an-cli/src/lib.rs
Fix typo with aom_keyframes
Docker-publish needs validate so if the tests do not pass the docker image is not published to dockerhub
> Fix aom_keyframes, docker-publish needs validate

- .devcontainer/devcontainer.json
- .github/workflows/tests.yml
- Dockerfile
- README.md
- av1an-cli/src/lib.rs
- av1an-encoder-constructor/src/lib.rs
- av1an-pyo3/src/lib.rs
- av1an/target_quality/target_quality.py
- Core
- Add back in probe-slow flag
- Readme
- Update with new rust flags
- Add --privileged to docker commands to remove Failed to genrate CPU mask with x265
- Devcontainer
- Add devcontainer for development in a container in vscode, This will allow anyone to develop and test their changes in vscode without having to install anything on their host besides docker.
- Dockerfile
- Moved around to allow for easier development. Requirements will be transferred by themselves and then installed so whenever one of the source files changes it will copy everything over and will only build maturin instead of constantly reinstalling rust and pip requirements.
- Action
- Add baseline-select to test if issues with encoders are related to vapoursynth or encoder in general
Closes #285
> Add probe slow, add devcontainer, update readme

- av1an-cli/src/lib.rs
- av1an-core/Cargo.toml
- av1an-core/src/ffmpeg.rs
- av1an-core/src/file_validation.rs
- av1an-core/src/lib.rs
- av1an-core/src/logger.rs
- av1an-core/src/progress_bar.rs
- av1an-core/src/split.rs
- av1an-core/src/target_quality.rs
- av1an-core/src/vmaf.rs
- av1an-encoder-constructor/src/lib.rs
- av1an-pyo3/Cargo.toml
- av1an-pyo3/pyproject.toml
- av1an-pyo3/src/lib.rs
- av1an-scene-detection/Cargo.toml
- av1an-scene-detection/src/av_scenechange.rs
- av1an-scene-detection/src/lib.rs
- av1an/chunk/chunk_queue.py
- av1an/manager/Manager.py
- av1an/manager/Pipes.py
- av1an/project/Project.py
- av1an/split.py
- cli/__main__.py
Also fixes some clippy warnings and adds `clippy::needless_pass_by_value` since that seems to be a common code smell here.
This new scene detector also works on vapoursynth input, and may be faster in many cases. On my laptop on 720p, av-scenechange is about 46% faster than pyscenedetect.
When compiling with `-C target-cpu=native` (which on my machine enables AVX2), the perf diff is up to 53% for the same clip. The performance can be further improved by compiling av1an with PGO.
> Add av-scenechange as the new and default scene detector

- av1an-core/src/lib.rs
This is a hard error in clippy,
so currently if compiled with clippy enabled,
compilation will fail. This commit allows compilation
with clippy enabled.
> Fix exact comparison of floats

- av1an-cli/src/main.rs
By default, ffmpeg re-encodes the audio to vorbis if no parameters are specified.
> Fix default audio parameters

- av1an-core/Cargo.toml
They changed the name of their master branch to "main",
so this fails to build if you don't have an existing Cargo.lock file.
> Update indicatif branch name

- av1an-cli/src/main.rs
- av1an-core/src/lib.rs
- av1an-core/src/vapoursynth.rs
- av1an-core/src/vmaf.rs
- av1an-pyo3/src/lib.rs
The `Project` struct now uses enums for `Encoder`, `SplitMethod`, and `ChunkMethod`, which is much faster than comparing up strings at runtime. This also removes many now useless functions that were wrappers around methods in `Encoder` itself which took a string as an argument.
> Fix some clippy warnings, use enums instead of strings

- av1an-core/src/lib.rs
- av1an-pyo3/src/lib.rs
Previously, `-e vpx` didn't work because the `possible_values` in clap didn't contain "vpx", but vpx in `Encoder` was serialized to "libvpx", making it impossible to actually use it from the command line. This PR fixes that, while also making the naming more consistent, as it is in line with "libaom" being called just aom in the CLI.
> Rename libvpx to vpx

- Cargo.lock
- av1an-core/Cargo.toml
- av1an-core/src/concat.rs
- av1an-core/src/ffmpeg.rs
- av1an-core/src/lib.rs
- av1an-core/src/progress_bar.rs
`DoneJson` is now a concurrent data structure, via `DashMap` and atomics
in the standard library. This should help avoid any potential race
conditions involved with one thread reading `done.json` while another
thread writes to it. Now, we only write to `done.json`, so any failure
from parsing the json while encoding is impossible.
The audio encoding is now done on a separate thread, and it is not
assumed that the audio encoding was finished if the `--resume` flag was
specified, which is now kept track of within `done.json`.
The initialization of the progress bar(s) now does not occur if the
corresponding initialization functions were not called, and the
functions to update the progress bar(s) are a NO-OP if it was not
initialized, rather than implicitly initializing it through the use of …
> Refactor: fix chunk restarting, progress bar, and potential race condition

- av1an-core/src/encoder.rs
- av1an-core/src/ffmpeg.rs
- av1an-core/src/lib.rs
- av1an-core/src/vmaf.rs
FFmpeg requires a very specific syntax to escape the file path in
Windows when using a filter, so this has been implemented with
conditional compilation. The behavior is the same on Windows, except
that the path is converted to an absolute path. Also, the only usage of
`std::env::current_dir` has been removed, since it was being used as an
ad-hoc way to convert a relative path to an absolute one, which doesn't
work if the temporary directory is in a different directory than the
current one.
We no longer kill the child processes from `process_pipe`,
since calling `wait` or `wait_with_output` closes the stdin handle
anyway.
Also, all usages of `cfg!(windows)` have been changed to `cfg!(target_os
= "windows")` to keep a consistent style.
> Fix target quality and VMAF plotting on Windows

- Cargo.lock
- av1an-scene-detection/Cargo.toml
This pulls in the scenechange improvements that were merged into rav1e some time ago.
> Bump av-scenechange to 0.6 (includes rav1e 0.5-beta)

- av1an-cli/src/lib.rs
- av1an-core/src/lib.rs
- av1an-scene-detection/src/av_scenechange.rs
Selectable with `--split-method av-scenechange-fast`.
The fast method enables downscaling the video before scene detection,
and uses av-scenechange's fast mode, which is similar to pyscenedetect.
This also removes the downscaling from the normal scenecut mode,
since downscaling does affect accuracy of the scene detection.
> Add a fast scenecut method option

- Cargo.lock
- av1an-cli/Cargo.toml
- av1an-cli/src/main.rs
- av1an-core/src/lib.rs
Errors now look like this:
```
Error: Input file "foo" does not exist!
```
instead of this:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Input file "foo" does not exist!', av1an-cli/src/main.rs:116:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
> Replace some panics with Err returns

- av1an-core/src/ffmpeg.rs
The old code used to search for the first match that looked like a frame
count. When ffmpeg emits a warning, it would also emit the frame count at
the point of warning, therefore the previous implementation gave wrong
frame count when it happened.
Fix this by modifying the code to take the last match. Also replace the
index of cap by an explicit one since this is the index of capture group
(which is constant given the regex), not matches.
> ffmpeg: fix frame count parsing

- av1an-core/src/encoder.rs
- av1an-core/src/ffmpeg.rs
- av1an-core/src/lib.rs
- av1an-core/src/util.rs
This should avoid some unnecessary overhead where regexes were being recompiled every time their respective function was called.
> Lazily compile all regexes, move macros to util module

- Cargo.lock
- av1an-cli/Cargo.toml
- av1an-cli/src/lib.rs
- av1an-cli/src/main.rs
- av1an-core/Cargo.toml
- av1an-core/src/broker.rs
- av1an-core/src/encoder.rs
- av1an-core/src/lib.rs
- av1an-core/src/target_quality.rs
- av1an-core/src/vapoursynth.rs
- av1an-core/src/vmaf.rs
Switch back to an old version of sysinfo, as 0.20 requires 1.54 to compile it, which is too new for MSYS2. Many minor simplifications.
We also switch to structopt for now instead of the beta release of clap, as clap officially recommends to not use the beta yet, and it caused some problems when compiling on Windows or with an older compiler.
Some minor changes:
- The `decow_strings` function has been removed, and we deal with `Cow<str>` properly now.
- The `remove_patterns` function now takes a mutable reference to a `Vec<String>` instead of copying one and modifing it to reduce complexity and overhead.
- The structs used to serialize the VMAF json result have been renamed to `VmafResult`, `Metrics`, and `VmafScore` (they were previously `Foo`, `Bar`, and `Baz`)
- Using an enum instead of …
> Refactoring, allow compiling with Rust 1.53

- Cargo.lock
- av1an-cli/Cargo.toml
It seems like these dependencies don't need to be specified to compile, as they are already specified in the root Cargo.toml.
> Remove other unused dependencies

- av1an-core/src/lib.rs
I had multiple cases in which concatenation using `mkvmerge` silently failed and av1an deleted the temp folder afterwards. I saw the `mkvmerge` process running in the background but it never wrote to the output file.
Of course the real fix should include further debugging and location of the problem with mkvmerge, but this patch at least prevents data loss. People can either join the files manually or simply run av1an with `--resume` without losing possible hundreds of hours of encoding time.
> Prevent data loss if concatenation failed

- av1an-core/src/project.rs
I found myself frequently having to look in the log file to see this,
and felt it would be more convenient to have it printed to the terminal.
This only affects verbose mode--normal mode will continue to print
this info to only the log file.
> Print scenechange info to stderr when in verbose mode

- av1an-core/src/project.rs
Because of the `scenes` variable updating,
this would print the number of scenes after
extra splitting twice instead of the number of scenes
before splitting and then the number after splitting.
> Fix printing on verbose scenechange info

- Cargo.lock
- av1an-cli/src/lib.rs
- av1an-core/Cargo.toml
- av1an-core/src/lib.rs
- av1an-core/src/project.rs
- av1an-core/src/scene_detect.rs
This leaves the default at medium, which is an improved version
of the current scenecut detection method.
The fast method has also been improved from its previous version.
The slow method is a completely new implementation, which has
been shown to be more accurate, but is also about 15% slower.
This also removes the av-scenechange-fast split method,
in favor of making a separate CLI option for --sc-method,
which can be set to "fast", "medium", or "slow".
This also adds a CLI option for scenecut downscaling,
which can be specified by providing a maximum height e.g.
--sc-downscale-height 720 to downscale any input which is
above 720p to 720p for scenecut detection.
This will avoid upscaling anything below 720p, because that
would just slow down scenecut detection for no benefit.
> Add new scenechange method

- av1an-cli/src/lib.rs
Fixes #359 and also is more clear that pressing enter will not overwrite.
> Fix confirmation prompt

- .github/workflows/tests.yml
- Cargo.lock
- Cargo.toml
- Dockerfile
- av1an-core/Cargo.toml
- av1an-core/src/encoder.rs
- av1an-core/src/ffmpeg.rs
- av1an-core/src/project.rs
This method uses ffprobe to count the number of packets
(which is identical to the number of frames, but faster)
in a video stream. This works with more video formats,
including with --enable-keyframe-filtering=2 in aomenc.
Performance should be similar or better than ffmpeg -copy.
Fixes #367
> Use a different method for ffmpeg frame count

- av1an-core/src/ffmpeg.rs
These functions were the easiest to convert. Transcoding with the API is significantly more complicated, and will be a work-in-progress.
> Rewriting simpler ffmpeg calls using the API

- av1an-cli/src/lib.rs
- av1an-core/src/broker.rs
- av1an-core/src/concat.rs
- av1an-core/src/encoder.rs
- av1an-core/src/ffmpeg.rs
- av1an-core/src/lib.rs
- av1an-core/src/scene_detect.rs
- av1an-core/src/settings.rs
- av1an-core/src/target_quality.rs
Mostly just stylistic changes/cleanups, but some notable changes:
- Validating encoder params now operates over string views of the original help text output rather than allocating new strings for everything
- The `Project` struct has been renamed to `EncodeArgs`, and the `project` module has been renamed to `settings`
> Fix many clippy warnings, many small code style changes

- Cargo.lock
- README.md
- av1an-cli/Cargo.toml
- av1an-cli/build.rs
- av1an-cli/src/lib.rs
- av1an-core/Cargo.toml
- av1an-core/src/concat.rs
- av1an-core/src/encoder.rs
- av1an-core/src/ffmpeg.rs
- av1an-core/src/progress_bar.rs
- av1an-core/src/scene_detect.rs
- av1an-core/src/settings.rs
- av1an-core/src/split.rs
- av1an-core/src/target_quality.rs
- src/main.rs
- Update dependencies
- Better documentation in `--help`
- Include git commit hash and more info in `--version`
- Add `-k` as shorthand for `--keep`
- Do not pass `ffmpeg_pipe` around everywhere
- Use macro to generate encoder bit depth functions
- Fix documentation in README
> Refactor: Better ffmpeg pipe handling + more info in --version

- README.md
I just put av1an into Arch Linux's [community] repository so this should be reflected in the README.
> Clean up installation instructions and add crates.io badge

- .github/workflows/tests.yml
- Cargo.lock
- Dockerfile
- av1an-cli/src/lib.rs
- av1an-core/src/concat.rs
- av1an-core/src/ffmpeg.rs
- av1an-core/src/settings.rs
- Require mkvmerge for x265, since we were actually concatenating x265 with ffmpeg by secretly creating an mp4 even if the file extension was mkv, and mp4 does not support certain types of subtitles that many sources have. ffmpeg cannot concatenate raw hevc bitstreams without the timestamps properly set without first creating an intermediate mp4 file, so for this reason we require mkvmerge to be used when using x265.
- Document behavior of how to encode separate audio tracks differently with this change, as using `-map` will not work and will probably cause unexpected results. All audio tracks and subtitles (technically, everything that isn't a video track) are copied by default now.
> Always copy subtitles and all audio tracks

- Cargo.lock
- av1an-core/Cargo.toml
- av1an-core/src/broker.rs
- av1an-core/src/chunk.rs
- av1an-core/src/encoder.rs
- av1an-core/src/lib.rs
- av1an-core/src/settings.rs
- av1an-core/src/split.rs
- av1an-core/src/target_quality.rs
- av1an-core/src/util.rs
- av1an-core/src/vapoursynth.rs
- av1an-core/src/vmaf.rs
The main change that this commit introduces is an `EncoderCrash` type
for errors, which also reports the stderr of the process piping to
the encoder so that it is easier to tell what the actual error is.
Target quality probe crashes are now properly logged with the
`EncoderCrash` type, replacing the old panicking code and making the
error significantly easier to read.
An "optimization" has been implemented which does not wait for the child
process piping to the encoder to exit, and instead collects its stderr
output asynchronously and immediately exits upon an encoder crash. This
does not yet apply to target quality probes, as there is not yet a
single interface for running an encoder (it is done manually for now).
This will change in the future, but this patch is getting too big for …
> Initial round of improvements for error handling

- Cargo.lock
- av1an-cli/src/lib.rs
- av1an-core/Cargo.toml
- av1an-core/src/broker.rs
- av1an-core/src/settings.rs
Introduces a new command line option called `--set-thread-affinity=n`,
where `n` specifies the number of threads to assign to each worker.
We use the `affinity` crate instead of the `nix` crate directly to
get abstractions for Windows and Linux.
> Allow setting thread affinity for each worker

- av1an-core/src/settings.rs
Previously, these warn statements came before we create
the temp directory. I'm assuming when the first log
statement is run, flexi_logger then attempts to create
the log file. If it fails, it doesn't try again.
Ensuring we create the temp directory before attempting
to log should resolve this issue.
> Fix a case where the log file could fail to be created

- av1an-cli/src/lib.rs
- av1an-core/src/settings.rs
Using fixed xterm 256 colors for grays can cause problems on some terminals with color schemes where the background is very close to the text, so we switch to using dimmed colors which should be much easier to read on a broader range of terminals.
> Use dimmed colors instead of fixed xterm 256 colors

- Cargo.lock
- av1an-cli/Cargo.toml
- av1an-cli/src/lib.rs
- av1an-core/src/broker.rs
- av1an-core/src/settings.rs
* Rename `--logging` to `--log-file` (`-l` shorthand still works)
* Introduce new `--log-level` option to set the log level filter
This change makes `--verbose` not log chunk starts and finishes, and
that information is not logged in the log file either unless
`--log-level=debug` is set. By default, `--log-level` is set to `info`.
The `debug` log level also logs the rav1e scenechange decision info
for each frame.
> Delegate chunk starts/finishes to debug log level, other logging changes

- av1an-core/src/concat.rs
- av1an-core/src/settings.rs
* Log the command used for concat (activated with log level `debug`)
(the command along with process output is logged again at log level
`error` if the command failed, regardless of `--log-level`)
* Replace some unwraps with `Result`s
* Add more `with_context()`s
> Improve error handling for concatenation

- Cargo.toml
Although the majority of av1an's time is spent
in third-party binaries, compiling with thin-LTO
does show up to a 10% improvement on scene detection
time. This will cause compilation to be slower.
However, thin-LTO has far less of a compilation time
impact than full LTO, while providing almost the same
speedups.
> Enable thin-LTO for release builds

- Cargo.lock
- av1an-cli/src/lib.rs
- av1an-core/src/broker.rs
- av1an-core/src/encoder.rs
- av1an-core/src/lib.rs
- av1an-core/src/progress_bar.rs
- av1an-core/src/settings.rs
- av1an-core/src/simd.rs
The SSE4.1/SSSE3 implementation of the parsing routines for
aomenc/vpxenc outperform the old regex by a factor of about 5000x
(3.5 μs vs. 0.7 ns to parse a single line on a Zen 1 1950x).
The idea is to eventually remove regex as a dependency entirely,
especially since there is an open PR to indicatif that speeds up the
template expansion (which replaces regexes with hand-written parsing).
In a future PR, different runtime SIMD detection mechanisms could
be explored further. We currently just use `is_x86_feature_detected!`,
but perhaps we could cache the result somehow for less overhead.
> Implement SSE4.1/SSSE3 SIMD-accelerated frame parsing for aomenc/vpxenc

- av1an-cli/src/lib.rs
- av1an-core/src/settings.rs
- av1an-core/src/target_quality.rs
Previously, the pixel format of the input file was checked every time
a chunk was started. Now, we just get the pixel format once at the
beginning and reuse it for all chunks.
> Perform input pixel format check only once

- av1an-core/src/concat.rs
We just needed to escape some characters, that is all.
> Fix ffmpeg concat with spaces or quotes on all platforms

- av1an-cli/src/lib.rs
- av1an-core/src/encoder.rs
With this PR, we'd change the minimum scene length to 24 frames as to make it more psycho-visually accurate if there are rapid scene-changes.
As for the 2nd part, disabling all kinds of temporal filtering and denoising in aomenc is a good idea for target-quality in itself, since we need the highest image possible out of a certain Q to evaluate quality properly, even if it creates more artifacts.
> Min chunk size to 24 and faster more accurate aomenc target-quality

- av1an-cli/src/lib.rs
- av1an-core/src/lib.rs
- av1an-core/src/scene_detect.rs
- av1an-core/src/settings.rs
I kind of wish that we wouldn't use clippy::pedantic and
clippy::nursery, as the number of `allow` lints at the top of src/lib.rs
is becoming quite absurd. However, I at least wanted to clear out the
large set of warnings being issued, regardless of that discussion.
> Fix all clippy warnings as of latest stable rustc

- av1an-core/src/broker.rs
- av1an-core/src/ffmpeg.rs
- av1an-core/src/lib.rs
- av1an-core/src/progress_bar.rs
- av1an-core/src/settings.rs
- av1an-core/src/vapoursynth.rs
This looks at the size of each chunk when it completes and saves that
size in kilobytes into the done.json file. For backwards compatibility
for encodes resumed from an earlier version of av1an, if the done.json
does not contain the chunk size, then on resume, av1an will lookup the
size of that chunk. The estimates on the progress bar also handle
resumes and chunk crashes gracefully.
> Add kbps and final file size estimates to progress bar

- av1an-core/src/encoder.rs
- av1an-core/src/target_quality.rs
This shouldn't cause any breaking changes since it doesn't affect (de)serialization and when resuming we don't read the probes again.
> Simplify target quality probe names

- av1an-core/src/parse.rs
- av1an-core/src/vmaf.rs
This avoids multiple deserialization of the same VMAF json file
when plotting the VMAF file by deserializing once and sorting,
but still using select_nth_unstable_by in the case of
read_weighted_vmaf which is now only called if we want a single
percentile out of the VMAF file.
This also corrects the plot which incorrectly stated that the 50th percentile
was the mean. It is still technically not the median though, since we
average the two center values in the case of an even number of elements.
> Avoid multiple deserialization of same VMAF json score file

- Cargo.lock
- av1an-core/Cargo.toml
- av1an-core/src/broker.rs
- av1an-core/src/settings.rs
aomenc has had a history of crashes related to TPL on certain
chunks, particularly in videos with less motion, such as animated
content. This commit enables a workaround to retry a chunk with TPL
disabled if such a crash is detected. Although there is some amount of
psychovisual quality loss with TPL disabled, this is preferable to being
unable to complete the encode.
> Retry chunk without TPL if a TPL-related crash occurs

- av1an-core/src/broker.rs
I think this would probably be good if somehow aomenc happens to crash *again* even with the tpl workaround. Realized this after I merged #444.
> Add extra conditional for tpl_crash_workaround

- Cargo.lock
- av1an-core/Cargo.toml
Indicatif replaced its regex with a hand-written parser, but this unfortunately breaks `wide_bar` and thus our progress bar. We will have to report an issue upstream about this, but until that is reported and fixed we have to use the old regex.
> `cargo update` + revert indicatif

- av1an-core/src/broker.rs
- av1an-core/src/ffmpeg.rs
- av1an-core/src/lib.rs
I disabled `clippy::needless_pass_by_value` since it's mostly catching false-positives nowadays (like complaining about a type that is technically not `Copy` but is just internally a `u64`, although it was useful in the beginning when there was a lot of passing `Vec<i32>` by value).
> Fix clippy warnings

- Cargo.lock
- av1an-core/Cargo.toml
The issue with the new parser has been fixed as of the latest commit, and the new parser is much faster than the old regex. `indicatif` now no longer depends directly on regex, but `console` still uses regex to parse ansi escape codes. Eventually it should be possible to remove regex entirely as a non-build/dev dependency.
> Update indicatif + `cargo update`

- .github/workflows/tests.yml
- Cargo.lock
- av1an-core/Cargo.toml
- av1an-core/src/encoder.rs
Currently, target quality requires a cq-level (or equivalent for the
encoder) arg to be present in order to work, so that it can replace the
existing cq-level with the new one. This commit makes it so that if the
arg is not present, av1an will insert it with the proper quality level.
> Automatically add cq-level arg if it is not present

- Cargo.lock
av-ivf was updated to nom 7. This removes several duplicate versions of
dependencies, reducing the total number of dependencies for av1an by 7.
> Bump av-ivf to 0.2.3

- av1an-core/src/vmaf.rs
Fixes a regression from 14836c0, where scores were sorted for more efficiently finding the percentile, resulting in a bizarre-looking VMAF graph.
> Fix vmaf plotting

- Cargo.lock
- av1an-cli/Cargo.toml
- av1an-core/Cargo.toml
This includes minor bumps to flexi_logger, sysinfo, vergen, and dashmap. In the past, I believe there were some issues with sysinfo that prohibited us from bumping it, but they seem to now be doing regular releases again to push out the bug fixes we needed. flexi_logger required an added feature to work around an issue with local time. We do not actually log times, but the interface in `LogWriter` requires passing `DeferredNow` which uses local time, which requires us to add this feature or have an obnoxious warning logged every time av1an starts.
> Regular dependency upgrades

- av1an-cli/src/lib.rs
- av1an-core/src/lib.rs
- av1an-core/src/progress_bar.rs
- av1an-core/src/scene_detect.rs
- av1an-core/src/settings.rs
- av1an-core/src/vapoursynth.rs
This PR mainly changes the behavior in 2 ways:
1. We now get the frame count and do scene detection in parallel. Initially, only the number of processed frames are shown, and the percentage stays at 100%, and the total frame count is 0. When the actual frame count is available, the progress bar is updated to reflect that. This can help I/O bound situations where the source is very large and the frame count takes a long time to calculate.
2. We also generate the vapoursynth cache in parallel with the scene detection and calculating the frame count. This eliminates the pause between scene detection and actual encoding (if vspipe finishes generating the cache in time, which will be the case 99% of the time, and it will still reduce the overhead in the very unlikely case that it hasn't …
> Remove overhead at the start and in between scene detection and encoding

- av1an-core/src/encoder.rs
> Remove max/min kf distance for aomenc and vpx

- Cargo.lock
- av1an-core/Cargo.toml
Indicatif recently fixed the somewhat strange behavior where the progress bar was printed with an extra line (https://github.com/mitsuhiko/indicatif/issues/334).
> Update indicatif and other dependencies

- av1an-core/src/concat.rs
- av1an-core/src/settings.rs
This will not fully fix mkvmerge on Windows yet but this should at least reduce the length of the executed mkvmerge command by using relative paths. A full fix that breaks up the mkvmerge command into multiple commands if there are too many chunks is coming later.
> Reduce length of mkvmerge command

- Cargo.lock
- Cargo.toml
- av1an-cli/Cargo.toml
- av1an-cli/src/lib.rs
- av1an-core/Cargo.toml
- av1an-core/src/lib.rs
Clap v3 has a derive proc macro very similar to the structopt one (enabled via the `derive` feature), so not that much work was needed to port everything over.
Changes from structopt:
- Adds help headings to organize the `--help` better
- `-v`/`--video-params`, `-f`/`--ffmpeg`, and `-a`/`--audio-params` all no longer require leading whitespace for the argument to be recognized. This means you can do e.g. `-v "--cpu-used=10 --rt"` and it will work without issues.
> Migrate to clap-v3

- av1an-cli/src/lib.rs
This was missed during the rebase between the photon-noise and clap v3
PRs.
> Move photon-noise to ENCODING header

- av1an-core/src/encoder.rs
- av1an-core/src/lib.rs
- av1an-core/src/settings.rs
Adds automatic tiling for aomenc, rav1e, svt-av1, vpx.
Encoder options are added if tiling is required.
Picture without tiles represented as (1, 1) tiles.
Tiles are set calculated from resolution, separately for horizontal and vertical resolution.
Default tile is 720 pixels, and tile calculation rounds down, so 1280x720 is (1,1) tiles, 1920x1080 is (2,1), and so on.
> Automatic tiling for default settings

- av1an-core/src/settings.rs
The total number of chunks is needed rather than the number of remaining chunks in the chunk queue (which discards completed chunks).
> Fix mkvmerge resuming

- av1an-core/src/encoder.rs
In `encoder.rs` there are a bunch of small but unnecessary heap allocations. We could make further improvements by using `SmallVec` in other places as well, but this should be good enough for a single PR.
> Remove some unnecessary allocations

- Cargo.lock
- Cargo.toml
- av1an-cli/Cargo.toml
- av1an-cli/src/lib.rs
Turns out the behavior is pretty much the same either way. This is probably left over from the initial port from python to rust, and as the rust version does not try to catch some sort of exception or something when pressing ctrl c, only one ctrl c is required for it to stop (a stark contrast to the python version).
> Remove ctrlc dependency

- Cargo.lock
- Cargo.toml
Currently av1an at the root directly will fail to compile from scratch or run e.g. cargo update. This fixes that issue.
> Fix av1an versions in root cargo toml

- README.md
The word "enocoder" has been changed to "encoder".
I think it's a typo, sorry if it's correct.
> Fixed a typo [enocoder => encoder]

- av1an-core/src/broker.rs
- av1an-core/src/settings.rs
- av1an-core/src/target_quality.rs
- av1an-core/src/vmaf.rs
This makes better error messages in the case of an ffmpeg pipe, where it would otherwise only display `pipe:: invalid data found when processing input` and the error from the encoder.
Here is an error message with this PR, showing the error from all 3 places:
```
ERROR [av1an_core::broker] [chunk 0] encoder crashed: exit status: 1
stdout:
stderr:
Fatal: Specify stream dimensions with --width (-w)  and --height (-h)
source pipe stderr:
Deprecated option --y4m specified, use -c y4m instead
Error: can only apply y4m headers to YUV and Gray format clips without alpha
Output 150 frames in 68280.21 seconds (0.00 fps)
ffmpeg pipe stderr:
pipe:: Invalid data found when processing input
```
> Display possible vspipe errors when ffmpeg pipe is present

- av1an-core/src/settings.rs
We need the total number of chunks for mkvmerge concat, not the number of completed chunks upon resuming.
> Fix mkvmerge concat

- av1an-core/src/concat.rs
Somehow I missed this in PR #523.
> Call fix_path for mkvmerge concat

- av1an-core/src/settings.rs
This pr check does user provide `--end-usage` and rate control values `--cq-level` or `--target-bitrate` when using custom commands and prints warning if they don't
.
> Encoder mode/rate check

- av1an-cli/src/lib.rs
I have no idea how this info disappeared from `--help`, but this adds it back.
> Re-add concat info to --help

- Cargo.lock
- av1an-core/Cargo.toml
The vapoursynth crate is still running on the deprecated failure crate. In my fork, I updated to thiserror + anyhow, and migrated to edition 2021. I opened a PR upstream: https://github.com/YaLTeR/vapoursynth-rs/pull/14
Not sure whether we want to leave this PR open until these changes are merged upstream or just merge it now (as this change reduces the number of dependencies by ~20). @shssoichiro thoughts?
> Update vapoursynth and other dependencies

- Cargo.lock
- av1an-cli/Cargo.toml
- av1an-cli/src/lib.rs
- av1an-core/Cargo.toml
- av1an-core/src/concat.rs
- av1an-core/src/scene_detect.rs
- av1an-core/src/settings.rs
- av1an-core/src/target_quality.rs
- Update log levels so that the log file contains more verbose
information by default, while leaving the stderr progress indicator
relatively uncluttered
- Explicitly set the log level to `error` for all dependencies
- rav1e scenechange info has been moved to `--log-level trace`
- Avoid outputting colors if stderr is not a tty
- Fix a crash when using `--quiet`
> Rework log levels to be more useful

- .mergify.yml
The way we have been doing releases does not coincide well with how we
have been utilizing our stable branch. Given that we release from
master, and that many people in the community use master on a daily
basis, it makes more sense for stable to always match the latest
released version, and for master to include unreleased changes which are
considered "stable".
For experiments, we should instead use a feature branch per experiment
until we are confident that it is ready to be merged into master.
> Do not automatically backport each PR to stable

- av1an-core/src/broker.rs
- av1an-core/src/progress_bar.rs
- av1an-core/src/settings.rs
The chunk index would be much more useful for users who are using
verbose mode. Worker index is easily derived from counting the lines,
and is not particularly useful.
> Display chunk index instead of worker index in verbose mode

- Dockerfile
This switches to using archlinux as the base image. The only issue is that rav1e is a bit out of date now (it's at version 0.4.1 in this container), but we can possibly fix that later. This should fix #426
> Fix ffmpeg issue in docker container

- av1an-core/src/encoder.rs
The old code will not work for future versions that use the same syntax, for example if there is a 0.9.1 version, as we only check for 0.9.0.
> Future proof SVT-AV1 version parsing

- Cargo.lock
- Cargo.toml
- av1an-core/Cargo.toml
- With https://github.com/xiph/rav1e/pull/2889 and https://github.com/xiph/rav1e/pull/2890, the cost based scene detection should be up to 40% faster, so we bring in those changes.
- The changes I made to vapoursynth-rs to move away from the deprecated failure crate have been merged, so we switch to upstream.
> Update rav1e and vapoursynth

- av1an-core/src/progress_bar.rs
The final audio size should be added to the `total_size / progress` rather than being counted as part of `total_size`. This used to sometimes cause initially extremely large estimates because of this issue.
> Fix progress bar size estimate

- Cargo.lock
- Cargo.toml
- av1an-cli/Cargo.toml
- av1an-cli/src/lib.rs
- av1an-core/Cargo.toml
- av1an-core/src/encoder.rs
- av1an-core/src/ffmpeg.rs
- av1an-core/src/lib.rs
- av1an-core/src/scene_detect.rs
- av1an-core/src/settings.rs
- av1an-core/src/target_quality.rs
- Also rename ffmpeg-next in Cargo.toml, and refer to our own ffmpeg module by `crate::ffmpeg`
> Update to ffmpeg 5.0

- .github/workflows/tests.yml
- av1an-cli/src/lib.rs
- av1an-core/src/settings.rs
This pull request adds the `--sc-only` boolean argument which forces av1an to stop after scene detection as per #573 
Right now it simply deletes the temporary directory after the run
What would be optimal would be to not create any temp dir if both:
1. The input is a vpy script.
2. -s is specified.
> Lastrosade sc only

- README.md
- av1an-cli/src/lib.rs
Sets extra splits to 10 * fps if extra splits option was not provided, defaults to 240 if failed to get fps
> Adaptive extra splits

- av1an-cli/src/lib.rs
Not setting this causes a panic instead of a proper error message in the case of not specifying any arguments.
> Set required for input

- av1an-core/src/encoder.rs
- av1an-core/src/parse.rs
- av1an-core/src/settings.rs
If a single chunk had >=10,000 frames, there would be a singular line of text causing the sse4.1 code to report a garbage value, which happened because of an invalid assumption that the number of digits of the buffered frames and encoded frames is always the same. This also affected the fallback function but in a non-obnoxious way, causing it to just return `None` in this edge case instead of a garbage value.
This PR fixes that issue, along with replacing the very suboptimal writes back to main memory (which caused `parse_encoded_frames` to be marked as `unsafe`) in the sse4.1 code with significantly more sensible masking of xmm registers based on the number of digits found.
> Replace memory writes with mask in sse4.1 aom/vpx parsing, fix edge case

- .github/workflows/tests.yml
- Dockerfile
Use caching for cargo build to reduce the build times from 5 mins to 45 seconds when dependencies are non changing
Restructure the entire Dockerfile to use multistaging to reduce the docker image by ~500 mb from 1.05 GB to 584 MB.
Use github action internal caching so we dont have to deal with uploading and download the cache as an artifact.
Use cargo chef to build all the dependencies as a layer so that can be cached and have to only compile av1an itself.
Without cargo chef after my initial changes cold run was 9m 49s and when caching the build times came down to 6m 28s but the cache would be invalided on any code change so it was not usable
With cargo chef on a cold run it was still 9m 49s and a cached run it came down to 4m 57s, since this  is caching the dependencies and still …
> Speed up CI, Reduce container image size

- .github/workflows/tests.yml
- Dockerfile
Action: 
- Use github cache action instead of using gha for the cache-from/to, this allows us to use the cache from the docker stage in the docker-publish stage and also doesnt show an artifact on the github action page. 
- Removed digest from docker stage as there is no digest since its not uploaded anywhere.
Docker:
- Reduce duplication so its easier to change the base image and add dependencies in a single place instead of in multiple place like before with the build dependencies.
- Removed rsync as that was a dependency I added when testing solutions around and isnt needed anymore
> Use github cache action instead of using gha. Dedupe Dockerfile

- av1an-core/src/util.rs
We intentionally transmute here for performance reasons.
> Silence remaining clippy lints

- Cargo.lock
- Cargo.toml
Decreases binary size by about 1.1 MB by avoiding regex as a transitive dependency.
- Switch to git console-rs, which rewrote the ANSI parser without regex, making it faster, and also significantly decreasing the binary size
- Also remove patch override of rav1e since av-scenechange already specifies a git version, so patching the version does not affect it
> Reduce binary size by removing regex

- Cargo.lock
- Cargo.toml
- av1an-cli/src/lib.rs
- av1an-core/Cargo.toml
- av1an-core/src/broker.rs
- av1an-core/src/chunk.rs
- av1an-core/src/encoder.rs
- av1an-core/src/lib.rs
- av1an-core/src/scene_detect.rs
- av1an-core/src/scenes.rs
- av1an-core/src/settings.rs
- av1an-core/src/split.rs
Currently implemented:
- Overriding the selected encoder & number of passes
- Overriding or adding video params
- Overriding photon noise setting
- Overriding min/max scene length
Closes #267
> Add zones support

- av1an-cli/src/lib.rs
- av1an-core/src/vapoursynth.rs
This makes it very easy for the user to tell whether or not lsmash or ffms2 is installed, which can help in debugging/troubleshooting situations as well.
> Include whether lsmash and ffms2 were found in version info

- Cargo.lock
- Cargo.toml
- av1an-cli/Cargo.toml
- av1an-core/Cargo.toml
The get_best_stream fix has been published in ffmpeg-next 5.0.3, so we can use it from crates.io now.
> Use published ffmpeg-next

- av1an-core/src/broker.rs
- av1an-core/src/settings.rs
I can't think of a situation where someone would want this issue to be
ignored, so we should treat it as any other encoder error and perform 3
retries, then exit if it continues to fail. This probably indicates some
kind of issue with decoding or applying filters to that chunk.
> Error and retry chunk if frame count mismatches

- av1an-core/src/ffmpeg.rs
If an input file contains any data streams audio encoding will fail when trying to write a non-supported stream to the intermediary mkv.  This removes any data streams found in the input.  
```
Output {
status: ExitStatus(
unix_wait_status(
256,
),
),
stdout: "",
stderr: "[matroska @ 0x565479976f00] Only audio, video, and subtitles are supported for Matroska.\nCould not write header for output file #0 (incorrect codec parameters ?): Invalid argument\nError initializing output stream 0:1 -- \n",
}
```
> Remove data streams when encoding audio

- av1an-core/src/scene_detect.rs
This way potential issues with input sources or filters can be caught sooner.
> Error if scene change frame count does not match

- Cargo.lock
- av1an-core/Cargo.toml
- av1an-core/src/grain.rs
- Fixes BT.1886 to use the more correct formula and gamma
- Simplify the `mid_tone` function
- Add quickcheck tests around `to_linear`/`from_linear`
> Improvements to grain synth gamma handling

- av1an-cli/src/lib.rs
Currently a missing input file will cause the encoder to panic later on. This change causes av1an to fail early with a clear error message.
> Print a proper error message if the input file does not exist

- av1an-core/src/lib.rs
- av1an-core/src/settings.rs
Currently this only applies to grain synth generation,
but the prior implementation of HDR detection only looked at the props
on the input video. Those may not necessarily be set correctly even if
the user is encoding to HDR, so we want to prioritize looking at the
encoder params, then fallback to checking the input if the user has not
set a transfer characteristic on the encoder.
> Improve selection of HDR content

- Cargo.lock
- Cargo.toml
- av1an-cli/Cargo.toml
- av1an-core/Cargo.toml
- av1an-core/src/broker.rs
- av1an-core/src/lib.rs
- av1an-core/src/settings.rs
- av1an-core/src/target_quality.rs
The [available_parallelism](https://doc.rust-lang.org/std/thread/fn.available_parallelism.html) function was made stable in Rust 1.59. This changeset makes use of it instead of the `num_cpus` crate. We still have transitive dependencies that use `num_cpus`, but we should still prefer to use stdlib code when possible.
This changeset also explicitly sets the minimum Rust version to 1.59. This was already the case, as it was required by Edition 2021, but now Cargo will show a helpful error message to users on an old-ish version.
> Use std::available_parallelism instead of num_cpus

- av1an-core/src/settings.rs
Sometimes with broken input `num_frames` fails to count frames and `.unwrap()` panics. Unfortunately since it panics in threaded code, this panic does not stop app from running and instead thread just hangs forever and tui shows some weird visual glitches.
> Don't panic if ffmpeg fails to count frames

- av1an-core/src/encoder.rs
Seems like it was copypasted from `x264`, but in `x265` some options are different. Plus added [`--analysis-reuse-file`](https://x265.readthedocs.io/en/master/cli.html#cmdoption-analysis-reuse-file) option which is used for [`--multi-pass-opt-analysis`](https://x265.readthedocs.io/en/master/cli.html#cmdoption-multi-pass-opt-analysis) and [`--multi-pass-opt-distortion`](https://x265.readthedocs.io/en/master/cli.html#cmdoption-multi-pass-opt-distortion) and ignored if neither specified.
> Fix x265 2-pass params

- av1an-cli/src/lib.rs
- av1an-core/src/target_quality.rs
I think target quality need a lot of work and improvement.
* vmaf_percentile to 1, 
* default vmaf rate to 1
> vmaf_percentile to 1, default vmaf rate to 1

- .github/workflows/windows-build.yml
Starting point for #530.
Builds an x64 executable and uploads it as a workflow artifact ([example run](https://github.com/FreezyLemon/Av1an/actions/runs/2504902829))
The [exact](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows) workflow trigger is still open for discussion. And maybe there's some way to automatically add the artifact to a release? Haven't looked into it yet, this is just the build.
Dependencies:
- Visual C++ Build Tools: pre-installed
- Python 3.10: pre-installed + setup by action for proper env variables
- NASM: Installed by action
- FFmpeg: Manual download (gyan.dev), cached via file hash
- VapourSynth: Manual download, cached via release version
Cargo packages are also cached. NASM could also be cached, but I didn't see it as a high …
> Create workflow for Windows x64 builds

- Dockerfile
Unfortunately cargo-chef no longer seems to work for this repository; it complains about a missing 'inherits' directive for the CI profile, even though it is not actually missing. Additionally, downgrading to previous versions also somehow causes errors.
Removing the CI profile fixes the docker build, however, since the scene detection is too slow for the CI in the debug build, and since we still would like overflow checking and debug *assertions* (and hence can't use the release profile), removing the CI profile is not a feasible workaround for this issue.
Therefore, the only solution for now seems to be to disable cargo-chef altogether, as being able to build via docker is preferable to being unable to do so at all, even if it is not as fast as it could be with docker layer caching.
> Temporarily disable docker caching via cargo-chef

- .github/workflows/windows-build.yml
Second part of #530.
First commit has some general improvements. The improved caching cuts the build time by around half.
Second commit kicks off the workflow on every push to `master` and automatically creates a prerelease with the Windows binary. This release is always called `latest` and can only exist once. This means the previous `latest` release will be deleted and then re-created with the new Windows binary. The latest release can always be found under the same URL (example https://github.com/FreezyLemon/Av1an/releases/tag/latest).
This does not cover full, tagged releases. But those can be made by downloading the last `av1an.exe` and manually attaching it to the release, which makes it easier, I think.
> Automate Windows binary releases on changes to master

- av1an-core/src/scene_detect.rs
- av1an-core/src/settings.rs
- av1an-core/src/vmaf.rs
This was deprecated quite a long time ago,
anyone who hasn't updated to a compatible version by now
is probably experiencing other errors due to plugins
being incompatible.
This should also eliminate the deprecation warning
that vspipe outputs, which confuses basically every person
who runs into an encoder crash while using av1an.
> Use `-c y4m` instead of deprecated `-y` in vspipe

- Cargo.lock
- av1an-cli/Cargo.toml
- av1an-core/Cargo.toml
This bumps the `ffmpeg-next` crate to 5.1.1, making it compatible with additions from ffmpeg release 5.1.
Note that this won't fix builds with the AUR package `ffmpeg-git`, because ffmpeg `master` has changes which already make it incompatible to crate version 5.1.1.
> Bump ffmpeg-next to 5.1.1

- .github/workflows/windows-build.yml
After FFmpeg release 5.1, gyan.dev updated their "latest" release from 5.0.1 to 5.1, which currently breaks the build (`ffmpeg-next` and `ffmpeg-sys-next` don't support 5.1 yet). To circumvent this in the future, I've fixed the version to 5.0.1 and switched to the GitHub mirror (older releases get removed from gyan.dev at some point).
This requires removing the cache functionality, because there's no way to get a file hash from GitHub release assets. This doesn't affect the build time much though.
I've [tested this on my fork already, and it works without a problem.](https://github.com/FreezyLemon/Av1an/actions/runs/2790530028)
Ignore the 2 commits, I'm just too lazy to squash them manually :D
> Fix CI Windows builds

- av1an-core/src/target_quality.rs
This is my first time making changes to Rust code, so let me know if the styling is wrong or if I made a glaring mistake with this change. It works perfectly on my machine
> Fix stalled pipe on Windows when using target quality

- av1an-core/src/progress_bar.rs
- av1an-core/src/settings.rs
Sometimes, `avg_frame_rate` returns NaN, which causes a divide-by-zero error in `extra_splits`. This PR fixes the behavior.
- Also fix other compiler warning.
> Fix extra_splits when fps is NaN

- Cargo.lock
- Cargo.toml
- av1an-cli/Cargo.toml
- av1an-core/Cargo.toml
- av1an-core/src/broker.rs
- av1an-core/src/concat.rs
- av1an-core/src/progress_bar.rs
- av1an-core/src/settings.rs
- av1an-core/src/split.rs
- av1an-core/src/target_quality.rs
- av1an-core/src/util.rs
- av1an-core/src/vmaf.rs
- docs/COMPILING.md
Notably:
- Update rav1e, av-scenechange, av-ivf and av-format
- Fix a variety of clippy lints
- Bump minimum rustc to 1.63 as required by other dependencies
This should in particular bring some speed improvements for the scenecut detection by pulling in speedups from rav1e's codebase.
> Various dependency updates and cleanup

- Cargo.lock
- av1an-core/Cargo.toml
tokio 1.21.0+ requires the `net` feature to be able to use `enable_io` on non-Unix platforms:
[1.20.0 docs](https://docs.rs/tokio/1.20.0/tokio/runtime/struct.Builder.html#method.enable_io) vs [1.21.0 docs](https://docs.rs/tokio/1.21.0/tokio/runtime/struct.Builder.html#method.enable_io).
So I enabled the feature and now the build [works](https://github.com/FreezyLemon/Av1an/actions/runs/3435210294) again.
> Fix Windows build

- av1an-core/src/progress_bar.rs
This fixes an issue where the fps and eta would not update until the very end of the encode.
See also console-rs/indicatif#493
> Temporarily disable steady ticks on progress bars

- av1an-core/src/progress_bar.rs
This also allows us to reenable steady tick.
I believe steady tick never worked as expected before, but given that it is working now, the tick duration of 100ms means that rendering the progress bar at 60hz is overkill, and we are fine with the default 20hz (which is arguably still overkill).
> Fix stuttering FPS and ETA on progress bar

- av1an-core/src/scenes.rs
- av1an-core/src/settings.rs
- av1an/src/main.rs
This adds a `--force-keyframes` flag which takes a comma-separated list of keyframes where av1an should force a scenecut. This can be useful for certain cases such as chapters (seeking improves significantly when chapter starts have keyframes).
> Add flag for forcing keyframes

- Cargo.lock
- av1an/Cargo.toml
- av1an/src/main.rs
This does somewhat change the appearance of the help text, but the order of options remains the same, headings have been changed to title case to match the new convention of clap 4, the full list of possible values is now populated automatically from the enum but is only displayed under `--help` (full help), among other changes to accommodate how clap 4 wants things.
> Update to clap 4

- Cargo.lock
- av1an-core/Cargo.toml
- av1an/Cargo.toml
After four months of radio silence from the maintainer of ffmpeg-next, we can only assume that the project is abandoned. Therefore, I've forked the crate into https://github.com/shssoichiro/ffmpeg-the-third. This also includes @FreezyLemon 's patchset to fix building on systems using ffmpeg-git.
> Migrate to new ffmpeg crate which fixes building against ffmpeg git

- av1an-core/src/parse.rs
On some rare inputs (that can happen in real world scenarios), this function panics. This PR fixes that issue. I have also fuzzed this function and the fallback `parse_aom_vpx_frames` and no other obvious panics or crashes seem to happen in debug mode, at least on the randomized inputs used in fuzzing.
> Fix panic in parse_aom_vpx_frames_sse41()

- Cargo.lock
- av1an-core/Cargo.toml
- av1an/Cargo.toml
The recent updates to the ffmpeg dependencies broke the `ffmpeg_static` feature to request linking against a static build of ffmpeg due to an upstream change in how the ffmpeg repo tagged releases [0].
v1.0.2 of the transitive ffmpeg-sys-the-third dependency includes the needed fix to get static ffmpeg builds to work again (at all) as well as to get static builds working on clang 16 [1].
\[0]: https://github.com/shssoichiro/ffmpeg-the-third/pull/3
\[1]: https://github.com/shssoichiro/ffmpeg-the-third/pull/5
> Upgrade `ffmpeg-the-third` and its transitive dependencies to fix static builds

- Cargo.lock
This fixes the building of the AUR package. Although I'm not in love with the AUR package being that fragile, I'd rather they remove `--locked`, but eh.
> Fix inconsistent cargo lock state

- av1an-core/src/encoder.rs
Because at least one user thought `format` was being used as a verb in this method name, and I can see how that can be somewhat confusing.
> Add a comment to the format method to clarify this refers to the video format

- .github/workflows/tests.yml
Addresses #719 
Adds a test to make sure target-quality is actually working by encoding at a target of 95 and 80 and then comparing to make sure the 95 version is bigger than the 80. In the event that it does fail it will also cat the log files to make sure so the developers can see what is happening and adjust the test or fix the issue if there is one. 
In this case we can see that there is no vmaf comparison happening and av1an is just doing a normal chunk encoding thus the two 95 and 80 are exactly the same size and is validated by the logs.
> Action: Test target-quality is working correctly.

- .github/workflows/tests.yml
Addresses #733 
This will update the latest tag on dockerhub when a release is published, it will also create sha images on all branches and will create a branch specific release for testing new features 
Adds version tags with major/major.minor tags
Updates the github action versions
Adds docker-publish step that will check for the dockerhub username and token secrets so docker-publish will only run if those are present
> Action: Tag latest, update versions, add docker-publish checker

- av1an-core/src/broker.rs
- av1an-core/src/progress_bar.rs
- av1an-core/src/settings.rs
This removes passing of audio_byte through functions and instead use functions from progress bar module to set and get static audio size bytes
> Move audio size to progress bar OnceCell

- Cargo.lock
This removes the transitive const_fn_assert dependency which was causing build issues for some users.
Closes #752
> Bump rav1e dependency

- av1an-core/src/lib.rs
- av1an-core/src/target_quality.rs
- Remove an allow for a lint that was merged into core
- Remove a vec which was written to but never read
> Fix rustc 1.71 clippy lints

- .github/workflows/windows-build.yml
- FFmpeg 5.1 -> 6.0
- VapourSynth R58 -> R63
- NASM 2.15.05 -> 2.16.01
- Small script improvements
I have no Windows installation accessible to me atm, so please check that VS R63 works with av1an before merging.
> CI: Update dependencies in Windows build

- README.md
- av1an-core/src/context.rs
- av1an-core/src/lib.rs
- av1an-core/src/settings.rs
- av1an-core/src/vapoursynth.rs
- av1an/src/main.rs
- docs/CLI.md
As the title suggests, adds two new chunking methods to Av1an.
The docs is a bit general and could be worked on a bit since I don't really want to say anything that could be misinformation about the technical details. The current chunk method order now is: DGDecNV > lsmash > ffms2 > bestsource > hybrid
[DGDecNV](https://www.rationalqm.us/dgdecnv/dgdecnv.html) requires an external program called "dgindexnv" to index the video first, though its [already bundled](https://www.rationalqm.us/dgdecnv/binaries/) with the binaries and plugins itself provided, and as the name suggests, it requires an NVIDIA GPU. Which also requires PureVideo, but that's ancient technology so everyone should have it anyway. And only decodes AVC/HEVC/MPG/VC-1.
BestSource is similar to select, its slow but should …
> Add DGDecNV and BestSource chunk method

- README.md
- av1an-core/src/context.rs
- av1an-core/src/lib.rs
- av1an-core/src/settings.rs
- av1an-core/src/vapoursynth.rs
- av1an/src/main.rs
- docs/CLI.md
Even though av1an does not distribute any binaries or libraries of DgDecNv, Donald A Graft, the author of DgDecNv, believes us to be in violation of the license.
Therefore, this commit removes DgDecNv support.
> Remove support for DgDecNv

- av1an/src/main.rs
When resuming, append to the log file instead of clearing its old contents.
I tested with and without resume.
> append to log file

- .github/workflows/windows-build.yml
- Update multiple actions to Node 20
- Switch to maintained softprops/action-gh-release
- Update to VS R66 and Python 3.12
- Use Swatinem/rust-cache instead of manual caching
- Remove FFmpeg/VS caching (caching doesn't save time)
> Update Windows CI job

- av1an-core/src/context.rs
- av1an-core/src/scenes.rs
- av1an-core/src/settings.rs
- av1an/src/main.rs
Fixes issue where vmaf plot was always ran if target-quality was set, this does not allow you to run vmaf plot without target-quality as it seems like vmaf plot was designed around target-quality at some point so --vmaf without --target-quality will do nothing. Decoupling the two seems like it will be a lot of work so I am adding this for now as it atleast closes #790 and the decoupling can happen later
> Fix vmaf flag check with target-quality

- av1an-core/Cargo.toml
- av1an-core/src/parse.rs
- av1an/Cargo.toml
- site/src/compiling.md
This is already the actual MSRV, but it was not updated in the Cargo config files, so this change is needed to fix CI.
> Bump MSRV to 1.70

- .github/workflows/windows-build.yml
Av1an prerelease windows binary doesn't support ffmpeg 7.0 because it wasn't build with ffmpeg 7.0
> Modify windows-build.yml to use ffmpeg 7.0

- av1an-core/src/ffmpeg.rs
I ran into an issue encoding certain mkv-files with multiple audio, subtitle and attachments, and managed to track down the issue to the way Av1an handles encoding audio; There's a lot of mapping weirdness done in [`ffmpeg.rs`](https://github.com/master-of-zen/Av1an/blob/master/av1an-core/src/ffmpeg.rs)'s `encode_audio` function:
https://github.com/master-of-zen/Av1an/blob/605bad6773025ceae938d48862e9cf99685d1d98/av1an-core/src/ffmpeg.rs#L166-L187
-that ends up giving me the following error when encoding, right after Scene detection:
```
[matroska @ 0x560b67fa86c0] Received a packet for an attachment stream.
[aost#0:6/copy @ 0x560b67ba16c0] Error submitting a packet to the muxer: Invalid argument
[out#0/matroska @ 0x560b67b935c0] Error muxing a packet
```
As such, I've trimmed out many of …
> Fix "Received a packet for an attachment stream" error when encoding certain files.

- Cargo.lock
- av1an-core/Cargo.toml
- av1an-core/src/scene_detect.rs
See https://github.com/rust-av/av-scenechange/pull/168
By avoiding piping, we gain significant performance improvements. The amount of improvement varies depending on the source video format, as this moves the bottleneck to be on the decoder, but tests showed anywhere from 20-75% improvement on 8-bit for the fast scenechange method, with smaller but still respectable improvements of up to 20% for 10-bit and for the standard scenechange method, compared to piping from `vspipe`.
Currently, this implementation is limited to Vapoursynth inputs, and does not work when using ffmpeg filters through av1an (this will fall back to using pipes).
> Implement pipeless scene detection for Vapoursynth inputs

- .cargo/config
- Cargo.lock
- av1an-core/Cargo.toml
- av1an/Cargo.toml
Standard dependency bump. Cargo was throwing a warning about `.cargo/config` needing to be migrated to a toml file. However, it seems this file was intended to be `.gitignore`d anyway, and there is nothing in the file that should need to be shared across machines (disabling multiplexing seems to have been a workaround for broken versions of curl, this was fixed in March 2023), so deleting it seemed to be the better option.
> Bump dependencies and remove an old file

- Cargo.lock
- av1an-core/Cargo.toml
- av1an-core/src/scene_detect.rs
This provides similar speedups as https://github.com/master-of-zen/Av1an/pull/844, but applies to video inputs not using Vapoursynth. For the time being, this still does not affect inputs using ffmpeg filters. This also does not yet use the padding implementation redzic mentioned to provide additional copy-avoidance. Those changes will hopefully come in future PRs.
> Implement pipeless scene detection for basic video inputs

- Dockerfile
Plugin doesn't exist on Arch repo anymore.
Fix https://github.com/master-of-zen/Av1an/issues/850
> Remove vapoursynth-plugin-lsmashsource

- site/src/compiling.md
Updating it since its out of date
Python is not needed if vapoursynth is portable
> Update compile docs

- av1an-core/src/chunk.rs
- av1an-core/src/context.rs
- av1an-core/src/lib.rs
- av1an-core/src/scene_detect.rs
- av1an-core/src/scenes.rs
- av1an-core/src/settings.rs
- av1an-core/src/target_quality.rs
- av1an-core/src/vapoursynth.rs
- av1an-core/src/vmaf.rs
- av1an/src/main.rs
- site/src/Cli/general.md
This adds support to use the `--arg key=value` argument through av1an.
Usage:
`av1an -i script.vpy --vspipe-args "source=video.mp4"`
`av1an -i script.vpy --vspipe-args "deinterlace=True" "source=video.mp4"`
The `Vec<String>` containing the input is saved in the `Vapoursynth` variant/struct of `Input`.
Changes are welcome.
Completes #528 .
> Add support for passing variables to the vspipe python environment

- Cargo.lock
- av1an-core/Cargo.toml
- av1an-core/src/context.rs
- av1an-core/src/util.rs
- av1an/Cargo.toml
- av1an/build.rs
- Update all dependencies to their latest version
- Fix new clippy lints from the latest rustc
- Fix an issue with the `select` chunk method introduced in ffmpeg 7
- The `SETPTS` seems unnecessary in all versions of ffmpeg, but in ffmpeg 7 it causes the filter to cut out the last several frames of the chunk
> Fix everything breaking the CI

- av1an-core/Cargo.toml
- av1an-core/src/util.rs
- av1an-core/src/vapoursynth.rs
> Use absolute instead of canonicalize for better Windows path handling

- .github/workflows/windows-build.yml
And remove unnecessary Python setup
> Update NASM and VapourSynth in windows-build.yml

- Cargo.lock
- av1an-core/Cargo.toml
- av1an-core/src/context.rs
- av1an-core/src/scene_detect.rs
- av1an/Cargo.toml
- av1an/src/main.rs
[`is_terminal`](https://doc.rust-lang.org/std/io/trait.IsTerminal.html#tymethod.is_terminal) is stable since 1.70 (MSRV is also 1.70).
The [atty crate](https://crates.io/crates/atty) is also unmaintained and has an [unfixed security issue](https://github.com/softprops/atty/issues/50)
> Replace atty crate with fn is_terminal from std

- README.md
The fork by Akarin appears to no longer be maintained, and is not compatible with ffmpeg7. Updated the link to the new recommended fork.
> Update lsmash link in Readme to ffmpeg7-compatible fork

- Cargo.lock
Includes a change that should fix #815. [diff](https://diff.rs/vapoursynth-sys/0.4.0/0.4.1/build.rs)
> lockfile: bump vapoursynth-sys to 0.4.1

- av1an-core/src/broker.rs
There is an edge case where a user may want to resume an encode after all chunks have completed. This is typically because all chunks finished encoding, but concatenation failed. This change removes an assertion which prevented that edge case from progressing. The assertion does not seem to be necessary, as the entire contents of this function are already wrapped in an `if` using the same condition as the assertion.
> Remove assertion that prevents resuming if all chunks are finished

- av1an-core/src/context.rs
- av1an-core/src/scenes.rs
- av1an-core/src/settings.rs
- av1an/src/main.rs
- site/src/Cli/vmaf.md
> Make --vmaf parameter work independently again

- .github/workflows/windows-build.yml
- site/src/compiling.md
I updated FFmpeg and VapourSynth in windows-build.yml
Made it so that updating FFmpeg doesn't cause the workflow to fail
I also fixed the release description not updating for the latest build (See [this](https://github.com/Uranite/Av1an/releases/tag/latest) for example)
I added LLVM to the compiling guide for Windows, because as it turns out, LLVM is required
Closes #840
> Windows build and compiling.md changes

- Cargo.lock
- av1an-core/Cargo.toml
- av1an-core/src/context.rs
- av1an-core/src/ffmpeg.rs
- av1an-core/src/scenes.rs
- av1an/Cargo.toml
Updates all dependencies to the latest versions,
except for nom, which requires some more code changes.
Closes #911
> Update dependencies and fix lints

- av1an-core/src/context.rs
- av1an-core/src/encoder.rs
- av1an-core/src/lib.rs
- av1an-core/src/scene_detect.rs
- av1an-core/src/vmaf.rs
The lints in `nursery` and `pedantic` are not intended to be stable, and many of them will be added or changed with each Rust update. This makes it annoying to maintain the package, because CI will begin failing every 6 weeks when a new Rust version releases. This cleans up this version's new pedantic lints, and then removes our overrides that enable the unstable lints.
It looks like this was already done in the `av1an` package a while ago, but we never did it for `av1an-core`.
> Fix clippy issues and stop it from breaking with every Rust update

- av1an-core/src/vapoursynth.rs
- Use `Display` trait instead of `Debug` for path formatting to preserve Unicode characters
- Wrap source path with r"" raw string literal in Python template
- Platform-safe escaping for Windows backslash characters
- Improve handling of special characters (\n, \t, etc.) in file paths
This should fix #920
> fix(av1an-core): fix path-handling in vapoursynth script

- av1an-core/src/context.rs
- av1an-core/src/encoder.rs
- av1an-core/src/lib.rs
- av1an-core/src/scenes.rs
- av1an-core/src/settings.rs
- av1an/src/main.rs
- site/src/Cli/encoding.md
- site/src/Cli/general.md
This improves upon setting default encoding parameters. The gist of this pull request is improving the tile and worker estimation, and keeping those values when setting video-params. My main use-case for this is that I sometimes have batches of mixed resolution videos (e.g. 1080p and 4k) that I want to encode with the same settings -- and not have to go through one by one to specify tile count.
Some of the commits are loosely related, and I wasn't sure if I should make separate pull requests for them, so they are included here. I am a beginner with rust, so please correct me if the formatting is bad, or if there is a better way to implement the changes.
> Improve setting default encode parameters

- site/src/Cli/general.md
Rather than just pasting the CLI help output, I formatted the general documentation to be a bit more like a browser page that is uniquely useful from the CLI output. At the top is a table of the arguments with each name linking to its respective section below with more details and examples as necessary. There's a couple of additional details added mostly for document consistency so it may need some adjustments.
I have only done the general page just as a starter to get some improvements in the Book so I'm very much open to suggestions. Once we agree on a solid preference for the format I can do the rest.
Thank you,
\- Boats M.
> Improve CLI documentation and formatting

- Cargo.lock
- av1an-core/Cargo.toml
- av1an-core/src/broker.rs
Sending `SIGINT` (pressing CTRL+C) while encoding currently terminates the chunk encoder, causing Av1an to retry the chunk and requiring the user to send multiple signals to terminate. This PR aims to bring that down to 1 command. There are also 2 open issues requesting that sending `SIGINT` should let the chunk(s) finish but not start any more until all are completed and Av1an exits early with no progress lost. That is the secondary goal for this PR but I'm not sure how to implement that yet.
This is a work in progress and there needs to be better logging for these new scenarios. It also needs to be applied in more parts of the code, such as in the Target Quality search before chunk encoding starts. I also need to test several different configurations like multiple input files, multiple …
> Add CTRL+C SIGINT handling

- README.md
- av1an/src/main.rs
- site/src/Cli/encoding.md
- site/src/Cli/general.md
- site/src/Cli/scene_detection.md
- site/src/Cli/target_quality.md
- site/src/Cli/vmaf.md
- site/src/av1an.md
This is a continuation of #962 for the remaining CLI documents. There are also fixes to the main readme.md - mainly updates to links and some grammar.
Next steps:
* Update inaccurate information on some of the chunking methods - docs suggest VS methods don't generate temporary files but they do (mainly indexing files)
* Update `av1an/src/main.rs` parameters to match the new documentation
* Reorder for consistency
* Update grammar (ex. "ffmpeg" must be "FFmpeg" to comply with license [checklist item 15](https://www.ffmpeg.org/legal.html#:~:text=Do%20not%20misspell%20FFmpeg%20(two%20capitals%20F%20and%20lowercase%20%22mpeg%22).))
* Make new pages to clean up main readme.md:
* Installation for more details on installing - doing this in readme would be too verbose
* Usage + examples - would …
> Improve CLI Documentation formatting

- av1an-core/src/broker.rs
- av1an-core/src/context.rs
- av1an-core/src/logging.rs
- av1an-core/src/target_quality.rs
A collection of fixes for logging:
* Large `Chunk` object will no longer be printed on every log during encoding - logs are no longer overly verbose or redundant (first log prints the `Av1anContext`)
* Add missing `use tracing` for Target Quality - Target Quality debug logs now work as expected
* Update old log to tracing during encoding - addresses issue where `--quiet` still logged it to terminal
* Fix log file objects have ANSI characters that cannot be displayed in files - log files objects are now more readable
* Target Quality VMAF target value is printed to the progress bar during target quality search for the chunk - addresses #934 but can be further improved to address a different issue
```
av1an.exe -i a.mkv --temp temporary --keep -w 2 -e svt-av1 --pix-format yuv420p -s a.json …
```
> Fix logging

- .gitignore
- av1an-core/src/broker.rs
- av1an-core/src/context.rs
- av1an-core/src/logging.rs
- av1an-core/src/progress_bar.rs
- av1an-core/src/scene_detect.rs
- av1an/src/main.rs
This changeset:
- Moves the console logs from stdout to stderr
- Readds the printing of number of chunks and encoder params to the default log level
- Adds a chunks counter to the progress bar
I would like to hide the span that gets printed on each log line, but I could not find a way to do this since we are using tracing_subscriber's layers to set up the logging.
Default:
Verbose:
> Further changes to console logging

- av1an-core/src/concat.rs
- av1an-core/src/context.rs
- av1an-core/src/encoder.rs
- av1an-core/src/ffmpeg.rs
- av1an-core/src/logging.rs
- av1an-core/src/scene_detect.rs
- av1an/src/main.rs
I found that the big blobs of debug info that were being printed on certain log lines, e.g. the resume logs, were a result of `tracing::instrument`. This change moves those all to debug level, so they are not printed to the console by default. This also cleans up a few other minor items, which are not necessary, but I already cleaned them up while debugging so I figured they are worth keeping.
> Move tracing instrumentation to debug

- av1an-core/src/broker.rs
- av1an-core/src/context.rs
When resuming, there is an issue where the total chunk count on the progress bar was incorrect. This was only affecting the progress bar and not the actual encode.
> Fix issue where chunk progress is inaccurate on resume

- Cargo.lock
- av1an-core/Cargo.toml
- av1an-core/src/encoder.rs
- av1an/Cargo.toml
- Sort dependencies in Cargo.toml files
- Bump most dependencies to their latest version, including most notably av-scenechange which removes the dependency on rav1e
This also required bumping the minimum rust version for the CLI from 1.81 to 1.82 due to multiple of its dependencies bumping their required version in a patch release.
> Cleanup and update dependencies

- av1an-core/Cargo.toml
- av1an-core/src/concat.rs
- av1an-core/src/context.rs
- av1an-core/src/encoder.rs
- av1an-core/src/ffmpeg.rs
- av1an-core/src/lib.rs
- av1an-core/src/logging.rs
- av1an-core/src/progress_bar.rs
- av1an-core/src/settings.rs
- av1an-core/src/target_quality.rs
- av1an-core/src/util.rs
- av1an-core/src/vapoursynth.rs
- av1an/src/main.rs
- Only make public the items that we actually want to expose for av1an as a library. Right now this is based on any items that are used by av1an's CLI. This may be expanded in the future.
- This allows us to enable a clippy lint for adding `#[inline]` to any public functions. The benefit of this is that those functions can be considered as candidates for inlining in the CLI even if LTO is not enabled.
> Cleanup and inline public exports

- av1an-core/src/concat.rs
- av1an-core/src/progress_bar.rs
This PR adds a check for an unsigned integer underflow condition when initializing a progress bar when resuming. If the condition occurs, the `resume_pos` is set to `resume_frames` instead of attempting to underflow the variable. I don't know why this subtraction occurs, so I have left it as-is when the underflow issue does not occur.
Resuming an encode initializes the progress bar with a state position of `0`, which causes the error below:
```ps
av1an -i .\a.mkv --temp resume --keep --resume -e svt-av1 -l logs/resume.log
INFO encode_file: Input: 1920x1080 @ 23.976 fps, YUV420P, SDR
INFO encode_file: encoding resumed with 9/19 chunks completed (10 remaining)
INFO encode_file:
Queue 10 Workers 2 Encoder svt-av1 Passes 1
Params: --preset 4 --keyint 0 --scd 0 --rc 0 --crf 25
thread 'main' …
```
> Fix resuming crashes from attempt to subtract with overflow

- av1an/src/main.rs
In target_quality.rs, `fn adapt_probing_rate()` is used to truncate the probing rate. This is not mentioned in the parameter description.
> Mention silent truncation of probing_rate>4

- codecov.yml
Eventually we would like to get full unit test coverage, but we are not there yet. So for now we just want the coverage reports to be informational.
> Make codecov not fail CI if coverage decreases

- av1an-core/src/concat.rs
- av1an-core/src/concat/tests.rs
- av1an-core/src/context.rs
Hi,
I use FFmpeg on an input filter to change fps of some of my clips: `--ignore-frame-mismatch --ffmpeg "-vf scale=-1:\\'min(ih,1080)\\':flags=lanczos,fps=15"`. After updating to newest master I found that fbba019e broke my method: since now, the output muxer is forced unconditionally to emit videos @ input fps, I get a video where e.g. with fps 60->15 The first 25% of the file play the whole video in 4x speed, and the last 75% are still image.
This PR would add a condition to only force output fps if `--ignore-frame-mismatch` is not set, since if you want to change output fps with FFmpeg you have to use this flag. I would also be down to add a flag to av1an to control fps forcing, or --- maybe even better --- add a flag to change fps directly through Av1an. This would additionally …
> fix fbba019e: forcing output FPS breaks using FPS changing filter

- av1an-core/src/settings.rs
Resolves #1003
Instead of bailing (exit with error message), present the user with a warning message (see below) that suggests they install mkvmerge or specify a different concatenation method. This allows users to perform Scene Detection without having to also specify a different concatenation method, which is unrelated to the user's intent.
The `tracing::warn` import was missing from the `settings.rs` file, so this PR also fixes that.
```ps
> av1an.exe -i input.mkv --temp temporary --concat mkvmerge --sc-only
WARN mkvmerge not found, but `--concat mkvmerge` was specified. Make sure to install mkvmerge or specify a different concatenation method (e.g. `--concat ffmpeg`) before encoding.
INFO resume was set but neither chunks.json nor done.json exist in temporary directory temporary
INFO …
```
> Fix CLI argument validation warnings do not print

- av1an-core/src/context.rs
- av1an-core/src/lib.rs
- av1an-core/src/scenes.rs
- av1an-core/src/scenes/tests.rs
- av1an-core/src/split.rs
- av1an-core/src/zones.rs
This creates a struct responsible for managing and generating the scenes list, and splits it into two separate lists, one pre-extra-splits and one post-extra-splits. We will use the pre-extra-splits list in the future for target quality.
> Refactor scene handling code

- .github/workflows/tests.yml
- av1an-core/src/context.rs
- av1an-core/src/progress_bar.rs
- av1an-core/src/scenes.rs
This change alters the format of the scenes.json file, which may cause resumes from prior versions of av1an to fail. Users should finish in-progress encodes before updating to this version.
> Fix loading of the scenes.json to load pre- and post- splits

- av1an-core/src/broker.rs
- av1an-core/src/settings.rs
- av1an-core/src/target_quality.rs
- av1an/src/main.rs
- site/src/Features/TargetQuality.md
Hammer the moldy chains that the developers shackled on the users. Put an end to the suffocating tyranny and give the users the long-awaited freedom.
Shatter the rigid constraints that imprisoned creative workflows in a cage of arbitrary limitations. Break free from the oppressive single-value targeting that forced users into narrow, inflexible quality corridors. Demolish the ancient walls of hardcoded tolerances that stood between encoders and their rightful control over quality ranges. Unleash the powerful flexibility that users have desperately craved, replacing the stale dictatorship of fixed thresholds with the sweet liberation of configurable boundaries.
- Replace fixed 1% tolerance with user-configurable target quality ranges
- Change `--target-quality` from single value to range …
> replace TQ tolerance with configurable ranges

- av1an-core/src/broker.rs
- av1an-core/src/chunk.rs
- av1an-core/src/context.rs
- av1an-core/src/ffmpeg.rs
- av1an-core/src/lib.rs
- av1an-core/src/scene_detect.rs
- av1an-core/src/scenes.rs
- av1an-core/src/scenes/tests.rs
- av1an-core/src/settings.rs
- av1an-core/src/target_quality.rs
- av1an-core/src/vapoursynth.rs
- av1an/src/main.rs
- Use one single Environment to get plugin info
- Avoid global state for plugins
- Initialize once at start of app
- Only instantiate one VS Environment or ffmpeg Input to get all clip info
- Cache clip info
> Refactor to reduce number of spawned Environments

- av1an-core/src/context.rs
Resolves #1056
The `Av1anContext` object stores the number of frames in the input. Currently it evaluates to 0, the initial value, and is not updated before zones are parsed. It should be removed and replaced with `args.input.clip_info()?.num_frames` instead.
Now that `clip_info` is retrieved and cached during validation, we can intialize the `Av1anContext` object with `args.input.clip_info()?.num_frames` instead of 0. When zones are parsed, the `Av1anContext.frames` value will be correct and `0` won't be used in place of the last frame in zones.
However, `clip_info` currently uses FFmpeg (used to cache the initial clip_info values) and it may disagree with the chosen VapourSynth chunking method and result in a frame mismatch:
```ps
> av1an.exe -i long.mkv --verbose --chunk-method dgdecnv …
```
> Fix zones replaces last frame with 0 and fails to parse

- Cargo.lock
- av1an/Cargo.toml
- av1an/src/main.rs
This PR adds a `--completions` flag. Invoking av1an with this flag prints completions for the specified shell to stdout.
> Add --completions flag to generate shell completions at runtime

- Cargo.lock
- Cargo.toml
- av1an-core/Cargo.toml
- av1an-core/src/context.rs
- av1an-core/src/encoder.rs
- av1an-core/src/ffmpeg.rs
- av1an-core/src/lib.rs
- av1an-core/src/scene_detect.rs
- av1an-core/src/scenes/tests.rs
- av1an-core/src/settings.rs
- av1an-core/src/target_quality.rs
- av1an-core/src/vapoursynth.rs
- av1an/Cargo.toml
- av1an/src/main.rs
This avoids the need to link against ffmpeg when building av1an, and instead uses the ffmpeg/ffprobe binaries in all places where we need it. We were already using the binaries in the majority of places, so this simply results in an improvement for setup for the end user, as linking against ffmpeg was a particular pain point.
> Remove dependency on the ffmpeg library

- av1an-core/src/context.rs
- av1an-core/src/metrics/vmaf.rs
- av1an-core/src/target_quality.rs
A user reported a problem where they couldn't use NEG and UHD features combined.
I could reproduce it and added the fix along with some improvements:
- Centralizes VMAF model selection logic into a single function instead of duplicating the same conditional logic across multiple places.
- Eliminates hardcoded model name checks by replacing exact string matching with simple detection
- Makes VMAF model selection consistent across all functions by ensuring the same feature-based logic is used everywhere
- Fixes inconsistent default model behavior where some cases used no model while others used hardcoded models
- Removes code duplication by replacing repeated match statements for model selection with a single reusable function
- Prepares the codebase for dynamic VMAF feature configuration …
> improve VMAF & small refactor

- Cargo.toml
- av1an-core/src/scene_detect.rs
- av1an-core/src/scenes.rs
- av1an-core/src/split.rs
- av1an-core/src/split/tests.rs
Reverts rust-av/Av1an#1060
There's some sort of issue with the distance calculation, so this needs more work. And tests.
> Revert "Add score-based enhanced extra splits method"

- av1an-core/src/target_quality.rs
Fix integer underflow when quantizer reaches 0 during target quality search
- Use `saturating_sub(1)` instead of unchecked subtraction to prevent wrap-around to `u32::MAX`
- Handle edge case when user specifies `--target-quality 0`
Convert `0` to `0.001` to avoid degenerate range [0, 0] that breaks interpolation
Prevents division by zero and interpolation failures in downstream calculations.
This practically allows the value of `0` to be usable for Butteraugli.
- Fixes crash when probing with `--qp-range 0-70` and unreachable quality targets
> fix: prevent integer underflow and handle zero TQ

- .gitattributes
Although git lfs would be ideal for storing the y4m file used in the integration tests, it is a pain in the rear. In addition to the additional cloning steps required, it is apparently breaking the AUR package for av1an-git. Therefore, removing it seems to be the simplest way forward.
> fix: remove git lfs

- site/src/Cli/target_quality.md
[vapoursynth-julek-plugin](https://github.com/dnjulek/vapoursynth-julek-plugin) doesn't support Norm-3 as confirmed in https://github.com/rust-av/Av1an/issues/1128. This is a simple PR to correct the offending line in the documentation.
> Clarify butteraugli-3 requirements

- Cargo.lock
- av1an-core/Cargo.toml
- av1an-core/src/context.rs
- av1an-core/src/loadscript.vpy
- av1an-core/src/scene_detect.rs
- av1an-core/src/vapoursynth.rs
- av1an/Cargo.toml
- Actually enable SIMD for scenecut detection. Oops.
- Always use the VapoursynthDecoder instead of piping to reduce memory bandwidth overhead.
- Use the default cachepath behavior (place the cache file next to the video), this avoids needing to re-cache if av1an's input hash changes, and for some reason is just faster.
With these fixes, av1an's SCD is now the same speed as av-scenechange.
> perf: improvements to scenecut detection speed
